import React from 'react';
import ImplementationLibrary from '../../components/architect/ImplementationLibrary';

const ROWS = [
  {
    id: 1,
    topic: 'AI Governance Framework',
    definition: 'Define AI control system',
    implementation: 'Adopt NIST AI RMF / ISO 42001',
    task: 'Establish policies and controls',
    service: 'Governance tools',
    deliverable: 'AI governance framework',
    validation: 'Compliance validation',
    testing: 'Audit tests',
    comparison: 'Ad-hoc vs governed AI',
    deployment: 'Org rollout',
    flow: 'AI → Governance',
  },
  {
    id: 2,
    topic: 'Responsible AI Principles',
    definition: 'Define ethical AI guidelines',
    implementation: 'Fairness, transparency, accountability',
    task: 'Document principles',
    service: 'Governance board',
    deliverable: 'AI ethics charter',
    validation: 'Stakeholder validation',
    testing: 'Policy tests',
    comparison: 'Undefined vs defined ethics',
    deployment: 'Org rollout',
    flow: 'AI → Ethics',
  },
  {
    id: 3,
    topic: 'AI Risk Management',
    definition: 'Identify and mitigate risks',
    implementation: 'Risk scoring (bias, privacy, hallucination)',
    task: 'Create risk register',
    service: 'Risk tools',
    deliverable: 'Risk report',
    validation: 'Risk validation',
    testing: 'Risk tests',
    comparison: 'Unknown vs managed risk',
    deployment: 'Continuous monitoring',
    flow: 'AI → Risk',
  },
  {
    id: 4,
    topic: 'Model Governance',
    definition: 'Manage model lifecycle',
    implementation: 'Versioning, approval, monitoring',
    task: 'Track model lifecycle',
    service: 'MLflow',
    deliverable: 'Model registry',
    validation: 'Version validation',
    testing: 'Model tests',
    comparison: 'Untracked vs governed models',
    deployment: 'CI/CD deploy',
    flow: 'Model → Lifecycle',
  },
  {
    id: 5,
    topic: 'Data Governance for AI',
    definition: 'Ensure trusted training data',
    implementation: 'Validate quality, lineage, consent',
    task: 'Govern training datasets',
    service: 'Unity Catalog',
    deliverable: 'Data governance report',
    validation: 'Data validation',
    testing: 'DQ tests',
    comparison: 'Raw vs governed data',
    deployment: 'Pipeline integration',
    flow: 'Data → AI',
  },
  {
    id: 6,
    topic: 'Bias Detection',
    definition: 'Identify bias in models',
    implementation: 'Evaluate across demographics',
    task: 'Build fairness metrics',
    service: 'ML tools',
    deliverable: 'Bias report',
    validation: 'Bias validation',
    testing: 'Bias tests',
    comparison: 'Biased vs fair model',
    deployment: 'Continuous monitoring',
    flow: 'Model → Bias',
  },
  {
    id: 7,
    topic: 'Fairness Enforcement',
    definition: 'Ensure equitable outcomes',
    implementation: 'Adjust model/weights/logic',
    task: 'Apply fairness constraints',
    service: 'ML tools',
    deliverable: 'Fair model',
    validation: 'Fairness validation',
    testing: 'Fairness tests',
    comparison: 'Biased vs fair outcomes',
    deployment: 'Model deployment',
    flow: 'Model → Fair',
  },
  {
    id: 8,
    topic: 'Explainability (XAI)',
    definition: 'Make AI decisions transparent',
    implementation: 'SHAP, LIME, feature attribution',
    task: 'Provide reasoning for outputs',
    service: 'ML tools',
    deliverable: 'Explainability report',
    validation: 'Explanation validation',
    testing: 'XAI tests',
    comparison: 'Black-box vs explainable',
    deployment: 'Feature deployment',
    flow: 'Input → Explanation',
  },
  {
    id: 9,
    topic: 'RAG Explainability',
    definition: 'Show source of answers',
    implementation: 'Provide citations from retrieved docs',
    task: 'Enable traceable answers',
    service: 'RAG system',
    deliverable: 'Source-backed response',
    validation: 'Source validation',
    testing: 'Retrieval tests',
    comparison: 'LLM vs RAG explainability',
    deployment: 'API deploy',
    flow: 'Query → Source',
  },
  {
    id: 10,
    topic: 'Transparency',
    definition: 'Provide clarity to users',
    implementation: 'Show model limitations and confidence',
    task: 'Build user-facing explanations',
    service: 'UI / API',
    deliverable: 'Transparency report',
    validation: 'User validation',
    testing: 'UX tests',
    comparison: 'Hidden vs transparent AI',
    deployment: 'UI release',
    flow: 'AI → User',
  },
  {
    id: 11,
    topic: 'Accountability',
    definition: 'Assign AI ownership',
    implementation: 'Define model owner, reviewer',
    task: 'Maintain responsibility',
    service: 'Governance tools',
    deliverable: 'Ownership mapping',
    validation: 'Owner validation',
    testing: 'Governance tests',
    comparison: 'No owner vs accountable AI',
    deployment: 'Metadata update',
    flow: 'AI → Owner',
  },
  {
    id: 12,
    topic: 'AI Auditability',
    definition: 'Track AI decisions and changes',
    implementation: 'Log inputs, outputs, model versions',
    task: 'Enable audit trail',
    service: 'MLflow / logs',
    deliverable: 'Audit logs',
    validation: 'Audit validation',
    testing: 'Audit tests',
    comparison: 'No audit vs traceable AI',
    deployment: 'Central logging',
    flow: 'AI → Audit',
  },
  {
    id: 13,
    topic: 'Human-in-the-Loop',
    definition: 'Add human oversight',
    implementation: 'Enable review/approval workflows',
    task: 'Reduce risk in decisions',
    service: 'Workflow tools',
    deliverable: 'HITL system',
    validation: 'Approval validation',
    testing: 'Workflow tests',
    comparison: 'Fully automated vs controlled AI',
    deployment: 'Workflow deployment',
    flow: 'AI → Human',
  },
  {
    id: 14,
    topic: 'Hallucination Control',
    definition: 'Reduce incorrect outputs',
    implementation: 'Use RAG, guardrails, validation',
    task: 'Detect hallucinations',
    service: 'RAG / LLM tools',
    deliverable: 'Hallucination report',
    validation: 'Output validation',
    testing: 'Adversarial tests',
    comparison: 'Raw LLM vs controlled AI',
    deployment: 'Runtime logic',
    flow: 'Query → Verified answer',
  },
  {
    id: 15,
    topic: 'Guardrails',
    definition: 'Control unsafe AI behavior',
    implementation: 'Apply content filters, policies',
    task: 'Prevent harmful outputs',
    service: 'LLM tools',
    deliverable: 'Guardrail system',
    validation: 'Safety validation',
    testing: 'Safety tests',
    comparison: 'Open vs controlled AI',
    deployment: 'Policy deployment',
    flow: 'Input → Filter',
  },
  {
    id: 16,
    topic: 'Prompt Governance',
    definition: 'Manage prompt versions and safety',
    implementation: 'Version prompts and templates',
    task: 'Control prompt usage',
    service: 'Git / MLflow',
    deliverable: 'Prompt registry',
    validation: 'Prompt validation',
    testing: 'Prompt tests',
    comparison: 'Ad-hoc vs managed prompts',
    deployment: 'CI/CD',
    flow: 'Prompt → AI',
  },
  {
    id: 17,
    topic: 'Privacy (AI)',
    definition: 'Protect personal data in AI',
    implementation: 'Mask PII, secure prompts/data',
    task: 'Apply privacy rules',
    service: 'Governance tools',
    deliverable: 'Privacy report',
    validation: 'Privacy validation',
    testing: 'Compliance tests',
    comparison: 'Raw vs protected AI',
    deployment: 'Policy rollout',
    flow: 'Data → AI',
  },
  {
    id: 18,
    topic: 'Consent Management',
    definition: 'Ensure user consent',
    implementation: 'Track consent for data usage',
    task: 'Enforce consent rules',
    service: 'Governance tools',
    deliverable: 'Consent registry',
    validation: 'Consent validation',
    testing: 'Compliance tests',
    comparison: 'No consent vs controlled',
    deployment: 'Policy deploy',
    flow: 'User → Data',
  },
  {
    id: 19,
    topic: 'Data Minimization',
    definition: 'Use only required data',
    implementation: 'Limit data used in AI pipelines',
    task: 'Reduce exposure risk',
    service: 'Governance tools',
    deliverable: 'Minimized dataset',
    validation: 'Validation',
    testing: 'Data tests',
    comparison: 'Full data vs minimal',
    deployment: 'Pipeline control',
    flow: 'Data → Filter',
  },
  {
    id: 20,
    topic: 'Security for AI',
    definition: 'Protect AI systems',
    implementation: 'Secure APIs, models, prompts',
    task: 'Apply IAM + encryption',
    service: 'IAM / Security tools',
    deliverable: 'Secure AI system',
    validation: 'Security validation',
    testing: 'Pen tests',
    comparison: 'Open vs secure AI',
    deployment: 'Policy rollout',
    flow: 'AI → Secure',
  },
  {
    id: 21,
    topic: 'Model Monitoring',
    definition: 'Track model performance',
    implementation: 'Monitor accuracy, drift, usage',
    task: 'Build dashboards',
    service: 'MLflow / Datadog',
    deliverable: 'Monitoring dashboard',
    validation: 'Metric validation',
    testing: 'Alert tests',
    comparison: 'Static vs monitored model',
    deployment: 'Continuous monitoring',
    flow: 'Model → Metrics',
  },
  {
    id: 22,
    topic: 'Drift Detection',
    definition: 'Detect model/data drift',
    implementation: 'Compare distributions over time',
    task: 'Trigger retraining',
    service: 'ML tools',
    deliverable: 'Drift report',
    validation: 'Drift validation',
    testing: 'Drift tests',
    comparison: 'Static vs adaptive AI',
    deployment: 'Continuous monitoring',
    flow: 'Model → Drift',
  },
  {
    id: 23,
    topic: 'Evaluation Framework',
    definition: 'Measure AI performance',
    implementation: 'Define metrics for accuracy, relevance',
    task: 'Build evaluation pipeline',
    service: 'MLflow',
    deliverable: 'Evaluation report',
    validation: 'Metric validation',
    testing: 'Eval tests',
    comparison: 'No eval vs governed eval',
    deployment: 'Pipeline deployment',
    flow: 'Output → Score',
  },
  {
    id: 24,
    topic: 'AI Testing (Responsible AI)',
    definition: 'Validate fairness, safety, robustness',
    implementation: 'Test edge cases and adversarial inputs',
    task: 'Build test suite',
    service: 'QA tools',
    deliverable: 'AI test report',
    validation: 'Test validation',
    testing: 'Adversarial tests',
    comparison: 'Untested vs validated AI',
    deployment: 'Release gating',
    flow: 'AI → Test',
  },
  {
    id: 25,
    topic: 'Incident Management (AI)',
    definition: 'Handle AI failures/issues',
    implementation: 'Define response plan',
    task: 'Manage AI incidents',
    service: 'SIEM / workflow',
    deliverable: 'Incident report',
    validation: 'Incident validation',
    testing: 'Simulation tests',
    comparison: 'Reactive vs structured',
    deployment: 'Incident workflow',
    flow: 'Issue → Resolution',
  },
  {
    id: 26,
    topic: 'Compliance Reporting',
    definition: 'Demonstrate compliance',
    implementation: 'Generate audit and compliance reports',
    task: 'Support regulators',
    service: 'BI tools',
    deliverable: 'Compliance dashboard',
    validation: 'Audit validation',
    testing: 'Compliance tests',
    comparison: 'No reporting vs audit-ready',
    deployment: 'Scheduled reporting',
    flow: 'AI → Compliance',
  },
  {
    id: 27,
    topic: 'Documentation',
    definition: 'Maintain AI documentation',
    implementation: 'Document models, data, risks, usage',
    task: 'Ensure transparency',
    service: 'Docs tools',
    deliverable: 'AI documentation',
    validation: 'Completeness validation',
    testing: 'Documentation tests',
    comparison: 'Undocumented vs documented',
    deployment: 'Continuous update',
    flow: 'AI → Docs',
  },
  {
    id: 28,
    topic: 'Governance Automation',
    definition: 'Automate governance processes',
    implementation: 'Auto-monitor, auto-audit, auto-report',
    task: 'Reduce manual effort',
    service: 'Databricks / APIs',
    deliverable: 'Automated governance',
    validation: 'Automation validation',
    testing: 'Automation tests',
    comparison: 'Manual vs automated',
    deployment: 'CI/CD integration',
    flow: 'AI → Auto-governed',
  },
  {
    id: 29,
    topic: 'Multi-Model Governance',
    definition: 'Manage multiple models',
    implementation: 'Track multiple LLMs/versions',
    task: 'Compare performance',
    service: 'MLflow',
    deliverable: 'Model comparison report',
    validation: 'Validation',
    testing: 'Comparison tests',
    comparison: 'Single vs multi-model',
    deployment: 'Controlled rollout',
    flow: 'Models → Compare',
  },
  {
    id: 30,
    topic: 'Business Value Governance',
    definition: 'Ensure AI delivers value',
    implementation: 'Track ROI, impact, adoption',
    task: 'Build KPI dashboards',
    service: 'BI tools',
    deliverable: 'AI value report',
    validation: 'KPI validation',
    testing: 'ROI tests',
    comparison: 'AI cost vs AI value',
    deployment: 'Continuous review',
    flow: 'AI → Business outcome',
  },
];

export default function AIGovernance() {
  return (
    <ImplementationLibrary
      pageTitle="AI Governance + Responsible AI — Implementation"
      pageSubtitle="30 AI governance patterns covering NIST AI RMF, bias, fairness, XAI, guardrails, LLMOps, RAG explainability, and responsible AI."
      statsLabel="AI Governance Topics"
      rows={ROWS}
      csvName="ai-governance-implementation.csv"
      accent="#f59e0b"
    />
  );
}
