import React from 'react';
import ImplementationLibrary from '../../components/architect/ImplementationLibrary';

const ROWS = [
  {
    id: 1,
    topic: 'Testing Strategy',
    definition: 'Define overall testing approach',
    implementation: 'Establish unit, integration, regression, and data testing layers',
    task: 'Align QA with pipeline stages',
    service: 'Databricks / QA framework',
    deliverable: 'Testing strategy doc',
    validation: 'Stakeholder validation',
    testing: 'Strategy review',
    comparison: 'Ad-hoc vs structured testing',
    deployment: 'Controlled rollout',
    flow: 'Pipeline → Testing',
  },
  {
    id: 2,
    topic: 'Unit Testing (Data)',
    definition: 'Validate individual transformations',
    implementation: 'Test SQL/PySpark logic at function level',
    task: 'Build test cases per transformation',
    service: 'PyTest / dbt tests',
    deliverable: 'Unit test suite',
    validation: 'Logic validation',
    testing: 'Unit tests',
    comparison: 'No tests vs unit-tested',
    deployment: 'CI integration',
    flow: 'Code → Test',
  },
  {
    id: 3,
    topic: 'Schema Validation',
    definition: 'Ensure structure consistency',
    implementation: 'Validate column names, types, nullability',
    task: 'Compare expected vs actual schema',
    service: 'Spark / dbt',
    deliverable: 'Schema validation report',
    validation: 'Schema match validation',
    testing: 'Schema tests',
    comparison: 'Flexible vs enforced schema',
    deployment: 'Automated pipeline',
    flow: 'Data → Schema',
  },
  {
    id: 4,
    topic: 'Data Quality Testing',
    definition: 'Validate correctness of data',
    implementation: 'Check nulls, duplicates, ranges, constraints',
    task: 'Implement DQ rules',
    service: 'Great Expectations / dbt',
    deliverable: 'DQ report',
    validation: 'Threshold validation',
    testing: 'DQ tests',
    comparison: 'No checks vs governed checks',
    deployment: 'Integrated pipeline',
    flow: 'Data → Quality',
  },
  {
    id: 5,
    topic: 'Source-to-Target Validation',
    definition: 'Ensure data correctness across layers',
    implementation: 'Compare source vs bronze/silver/gold',
    task: 'Build reconciliation queries',
    service: 'SQL / Databricks',
    deliverable: 'Reconciliation report',
    validation: 'Data match validation',
    testing: 'Reconciliation tests',
    comparison: 'Trust assumption vs verified data',
    deployment: 'Scheduled jobs',
    flow: 'Source → Target',
  },
  {
    id: 6,
    topic: 'Transformation Testing',
    definition: 'Validate business logic',
    implementation: 'Test joins, aggregations, filters',
    task: 'Verify transformation accuracy',
    service: 'Spark SQL',
    deliverable: 'Transformation validation',
    validation: 'Logic validation',
    testing: 'Functional tests',
    comparison: 'Untested vs verified logic',
    deployment: 'CI/CD pipeline',
    flow: 'Raw → Transformed',
  },
  {
    id: 7,
    topic: 'SCD Testing',
    definition: 'Validate historical data logic',
    implementation: 'Test Type 1/2/3 implementations',
    task: 'Check history correctness',
    service: 'Delta Lake',
    deliverable: 'SCD validation report',
    validation: 'History validation',
    testing: 'SCD tests',
    comparison: 'Overwrite vs history tracking',
    deployment: 'Automated jobs',
    flow: 'Change → History',
  },
  {
    id: 8,
    topic: 'Deduplication Testing',
    definition: 'Validate duplicate removal',
    implementation: 'Ensure unique records',
    task: 'Test business-key dedup logic',
    service: 'Spark / SQL',
    deliverable: 'Dedup report',
    validation: 'Uniqueness validation',
    testing: 'Duplicate tests',
    comparison: 'Raw vs deduped',
    deployment: 'Pipeline integration',
    flow: 'Data → Clean',
  },
  {
    id: 9,
    topic: 'Incremental Load Testing',
    definition: 'Validate incremental pipelines',
    implementation: 'Test CDC/watermark logic',
    task: 'Compare full vs incremental output',
    service: 'Delta Lake',
    deliverable: 'Incremental test report',
    validation: 'Delta validation',
    testing: 'Incremental tests',
    comparison: 'Full vs incremental',
    deployment: 'Scheduled jobs',
    flow: 'Change → Update',
  },
  {
    id: 10,
    topic: 'Partition Testing',
    definition: 'Validate partition logic',
    implementation: 'Ensure correct partition creation and pruning',
    task: 'Check partition balance',
    service: 'Delta Lake',
    deliverable: 'Partition report',
    validation: 'Partition validation',
    testing: 'Query tests',
    comparison: 'No partition vs optimized',
    deployment: 'Config deploy',
    flow: 'Data → Partition',
  },
  {
    id: 11,
    topic: 'Performance Testing',
    definition: 'Validate pipeline performance',
    implementation: 'Measure runtime, throughput, latency',
    task: 'Benchmark jobs',
    service: 'Databricks / Spark',
    deliverable: 'Performance report',
    validation: 'SLA validation',
    testing: 'Load tests',
    comparison: 'Untuned vs optimized',
    deployment: 'Continuous tuning',
    flow: 'Job → Performance',
  },
  {
    id: 12,
    topic: 'Volume Testing',
    definition: 'Test large-scale data handling',
    implementation: 'Simulate high data volume',
    task: 'Validate scalability',
    service: 'Databricks',
    deliverable: 'Volume test report',
    validation: 'Throughput validation',
    testing: 'Stress tests',
    comparison: 'Small vs large scale',
    deployment: 'Controlled test env',
    flow: 'Data → Scale',
  },
  {
    id: 13,
    topic: 'Streaming Testing',
    definition: 'Validate real-time pipelines',
    implementation: 'Test latency, offsets, ordering',
    task: 'Verify streaming correctness',
    service: 'Kafka / Event Hub',
    deliverable: 'Streaming test report',
    validation: 'Offset validation',
    testing: 'Streaming tests',
    comparison: 'Batch vs streaming',
    deployment: 'Continuous job',
    flow: 'Stream → Output',
  },
  {
    id: 14,
    topic: 'API Testing (Data Ingestion)',
    definition: 'Validate API-based data',
    implementation: 'Test API response, schema, rate limits',
    task: 'Validate ingestion accuracy',
    service: 'Postman / Python',
    deliverable: 'API test report',
    validation: 'Response validation',
    testing: 'API tests',
    comparison: 'Mock vs real API',
    deployment: 'CI/CD',
    flow: 'API → Data',
  },
  {
    id: 15,
    topic: 'Error Handling Testing',
    definition: 'Validate failure scenarios',
    implementation: 'Simulate job failures and retries',
    task: 'Test recovery logic',
    service: 'Databricks workflows',
    deliverable: 'Error test report',
    validation: 'Failure validation',
    testing: 'Chaos testing',
    comparison: 'Fail-fast vs resilient',
    deployment: 'Automated jobs',
    flow: 'Error → Recovery',
  },
  {
    id: 16,
    topic: 'Data Drift Testing',
    definition: 'Detect data pattern changes',
    implementation: 'Compare historical vs current distribution',
    task: 'Identify anomalies',
    service: 'MLflow / custom',
    deliverable: 'Drift report',
    validation: 'Drift validation',
    testing: 'Drift tests',
    comparison: 'Static vs monitored data',
    deployment: 'Continuous monitoring',
    flow: 'Data → Drift',
  },
  {
    id: 17,
    topic: 'Regression Testing',
    definition: 'Ensure stability after changes',
    implementation: 'Re-run tests after updates',
    task: 'Compare results over time',
    service: 'CI/CD tools',
    deliverable: 'Regression report',
    validation: 'Result comparison',
    testing: 'Regression tests',
    comparison: 'No regression vs stable system',
    deployment: 'Automated pipeline',
    flow: 'Change → Stability',
  },
  {
    id: 18,
    topic: 'End-to-End Testing',
    definition: 'Validate full pipeline',
    implementation: 'Test ingestion → modeling → BI flow',
    task: 'Ensure business output correctness',
    service: 'Databricks / BI tools',
    deliverable: 'E2E test report',
    validation: 'Output validation',
    testing: 'E2E tests',
    comparison: 'Partial vs full validation',
    deployment: 'Release pipeline',
    flow: 'Source → Dashboard',
  },
  {
    id: 19,
    topic: 'BI Testing',
    definition: 'Validate dashboards and reports',
    implementation: 'Check KPI, filters, drill-down logic',
    task: 'Ensure correct reporting',
    service: 'Power BI / Tableau',
    deliverable: 'BI validation report',
    validation: 'KPI validation',
    testing: 'UI + data tests',
    comparison: 'Visual-only vs verified reports',
    deployment: 'BI release',
    flow: 'Data → Report',
  },
];

export default function DataTestingImplementation() {
  return (
    <ImplementationLibrary
      pageTitle="Data Testing — Enterprise Implementation"
      pageSubtitle="19 testing patterns covering unit, schema, DQ, reconciliation, SCD, performance, streaming, regression, E2E, and BI testing."
      statsLabel="Testing Topics"
      rows={ROWS}
      csvName="data-testing-implementation.csv"
      accent="#0891b2"
    />
  );
}
