import React from 'react';
import ChallengeLibrary from '../../components/architect/ChallengeLibrary';

const CHALLENGES = [
  // ── Cluster / Compute (1-10) ────────────────────────────────────────
  {
    id: 1,
    title: 'Cluster Not Starting',
    description: 'Cluster stuck in PENDING state for 15+ minutes',
    scenario: 'Instance quota exhausted in region; cluster waiting for capacity',
    impact: 'All scheduled jobs delayed, SLA breach',
    rootCause: 'Cloud instance quota hit or AZ capacity issue',
    solution: 'Increase instance quota, spread across AZs, use cluster pools',
    tools: 'Cloud quota request, Databricks cluster pools',
  },
  {
    id: 2,
    title: 'Driver Node OOM',
    description: 'Driver crashes with OutOfMemoryError mid-job',
    scenario: 'collect() pulling 10M rows to driver; notebook displaying large result',
    impact: 'Job failure, partial writes, data inconsistency',
    rootCause: 'Large data pulled to driver via collect/toPandas/show',
    solution: 'Use spark.sql.execution.arrow, avoid collect, increase driver mem',
    tools: 'Spark UI driver metrics, broadcast threshold tuning',
  },
  {
    id: 3,
    title: 'Executor OOM',
    description: 'Executors killed, job retries, cost spike',
    scenario: 'Join producing cartesian product; skewed key on one executor',
    impact: 'Slow jobs, cost spike, retry storm',
    rootCause: 'Data skew, insufficient memory per executor, broadcast too large',
    solution: 'Enable AQE skew join, salt keys, increase memory, broadcast threshold',
    tools: 'Spark UI, AQE, salting',
  },
  {
    id: 4,
    title: 'Spot Instance Reclaimed',
    description: 'Mid-job executor loss from spot reclaim',
    scenario: 'Cloud reclaims spot capacity during peak; 20% of executors gone',
    impact: 'Job rerun, SLA miss for batch window',
    rootCause: 'Using spot for time-sensitive workload',
    solution: 'Mixed instance policy (on-demand driver, spot executor), fallback strategy',
    tools: 'Cluster policy: first_on_demand, spot_bid_price_percent',
  },
  {
    id: 5,
    title: 'Cluster Auto-Termination Mid-Job',
    description: 'Cluster terminated while long job still running',
    scenario: 'Auto-termination set too aggressive on All-Purpose cluster',
    impact: 'Job failure mid-execution, no result',
    rootCause: 'Wrong cluster type (All-Purpose for long batch)',
    solution: 'Use Job Clusters for scheduled workloads; tune idle termination',
    tools: 'Job cluster config, auto_termination_minutes',
  },
  {
    id: 6,
    title: 'Init Script Failure',
    description: 'Cluster fails to start due to init script error',
    scenario: 'Init script referencing removed package or expired cert',
    impact: 'Cluster unavailable, jobs queued indefinitely',
    rootCause: 'Unpinned dependencies, expired credentials, deprecated syntax',
    solution: 'Pin versions, test init scripts in dev, rotate credentials',
    tools: 'Init script logs in driver logs, cluster-scoped vs global init',
  },
  {
    id: 7,
    title: 'Library Install Failure',
    description: 'PyPI / Maven library install fails on cluster',
    scenario: 'PyPI outage or dependency conflict during cluster startup',
    impact: 'Cluster starts but jobs fail at import',
    rootCause: 'Version conflict, network issue, missing dependency',
    solution: 'Use cluster-scoped libraries, pin versions, build custom Docker image',
    tools: 'Databricks cluster libraries UI, Container Services',
  },
  {
    id: 8,
    title: 'Cluster Stuck Terminating',
    description: 'Cluster shows TERMINATING for hours',
    scenario: 'Long shutdown hook, driver unresponsive, cloud API lag',
    impact: 'Cannot reuse cluster name, metric noise',
    rootCause: 'Shutdown hook hanging, driver OOM during shutdown, cloud API lag',
    solution: 'Force-terminate via API, investigate shutdown hooks',
    tools: 'Databricks REST API /clusters/permanent-delete',
  },
  {
    id: 9,
    title: 'Pool Exhausted — Slow Start',
    description: 'Cluster takes 10+ min to start despite pool',
    scenario: 'Pool size too small for peak concurrent demand',
    impact: 'Ad-hoc query latency, user frustration',
    rootCause: 'Pool min_idle too low, max_capacity hit',
    solution: 'Right-size pool, monitor idle_count, use preloaded_spark_versions',
    tools: 'Pool metrics, cluster start time monitoring',
  },
  {
    id: 10,
    title: 'Wrong Cluster Mode',
    description: 'Standard cluster used for multi-user workload',
    scenario: 'Analytics team sharing Standard cluster causing credential collisions',
    impact: 'Wrong identity propagated, governance failure',
    rootCause: 'Using Standard instead of Shared (High Concurrency)',
    solution: 'Use Shared access mode for multi-user; Single User for jobs',
    tools: 'UC cluster access modes',
  },

  // ── Jobs & Workflows (11-20) ────────────────────────────────────────
  {
    id: 11,
    title: 'Job Failed With No Error Log',
    description: 'Job shows FAILED but log viewer empty',
    scenario: 'Driver OOM before logging initialized; log sink unreachable',
    impact: 'Impossible to RCA, repeated failures',
    rootCause: 'Log sink failure, driver crash pre-logging, log retention expired',
    solution: 'Enable cluster log delivery, persistent logs to DBFS/S3, early logging',
    tools: 'Cluster log delivery config, audit logs',
  },
  {
    id: 12,
    title: 'Infinite Retry Loop',
    description: 'Job retries forever on transient failure',
    scenario: 'Flaky source API failing 50% of time; retry policy unbounded',
    impact: 'Cost spike, alert fatigue, downstream delay',
    rootCause: 'No max_retries limit, no exponential backoff',
    solution: 'Set max_retries, exponential backoff, circuit breaker',
    tools: 'Job task retry config, custom retry framework',
  },
  {
    id: 13,
    title: 'Concurrent Run Limit Hit',
    description: 'New runs queued because max concurrent hit',
    scenario: 'Long-running job blocking new triggers; upstream delay cascade',
    impact: 'Downstream pipelines delayed, SLA miss',
    rootCause: 'max_concurrent_runs=1, long-running task',
    solution: 'Increase max_concurrent_runs with idempotency, or fix slow task',
    tools: 'Job definition max_concurrent_runs',
  },
  {
    id: 14,
    title: 'Job Not Triggered by Schedule',
    description: 'Cron job skipped overnight run',
    scenario: 'Daylight saving transition; cron expression ambiguous',
    impact: 'Missing data for one day, SLA breach',
    rootCause: 'DST transition, timezone misconfiguration, workspace paused',
    solution: 'Use UTC cron, explicit timezone, scheduler monitoring',
    tools: 'Job schedule config timezone=UTC',
  },
  {
    id: 15,
    title: 'Task Timeout',
    description: 'Task killed by timeout before completion',
    scenario: 'Increased data volume pushing past configured timeout',
    impact: 'Incomplete data, partial writes if not atomic',
    rootCause: 'Hardcoded timeout not scaled with volume, slow query',
    solution: 'Tune timeout_seconds, optimize query, split task',
    tools: 'Job task timeout_seconds',
  },
  {
    id: 16,
    title: 'Notebook Not Found (Git Sync)',
    description: 'Job fails with "notebook not found" after Git pull',
    scenario: 'Feature branch merged with file rename; job path not updated',
    impact: 'Pipeline failure after deploy',
    rootCause: 'Git repo updated but job definition references old path',
    solution: 'Parameterize notebook path, CI/CD updates job defs',
    tools: 'Databricks Repos, Asset Bundles (DAB)',
  },
  {
    id: 17,
    title: 'Task Dependency Broken',
    description: 'Downstream task runs before upstream completes',
    scenario: 'Task dependency graph edited manually; depends_on missing',
    impact: 'Wrong data read, downstream failure',
    rootCause: 'depends_on misconfigured in job definition',
    solution: 'Define explicit depends_on, use multi-task jobs correctly',
    tools: 'Job multi-task workflow DAG',
  },
  {
    id: 18,
    title: 'Job Cluster Reuse Not Working',
    description: 'Each task spins new cluster instead of reusing',
    scenario: 'Task uses library conflict; new cluster per task',
    impact: 'Startup cost per task, 10x runtime',
    rootCause: 'job_cluster_key mismatch, library conflict',
    solution: 'Use shared job_cluster_key across tasks',
    tools: 'Job definition job_clusters + job_cluster_key',
  },
  {
    id: 19,
    title: 'Job Cost Spike',
    description: 'Single job consuming 10x expected DBU',
    scenario: 'Runaway query with cartesian join; no cost limit',
    impact: 'Budget blown, FinOps alert',
    rootCause: 'Bad query plan, no cluster policy cap, All-Purpose cluster used',
    solution: 'Cluster policies with max_dbu, query profile review, alerts',
    tools: 'Cluster policies, system.billing.usage',
  },
  {
    id: 20,
    title: 'Job Succeeded But No Data Written',
    description: 'Job GREEN but target table unchanged',
    scenario: 'Filter producing empty result; silent success',
    impact: 'Silent data failure, consumer gets stale data',
    rootCause: 'Logic returning empty, upstream source empty, write path wrong',
    solution: 'Post-write row count check, fail-on-zero assertion',
    tools: 'DLT expectations, post-write validation',
  },

  // ── Delta Lake / Storage (21-30) ────────────────────────────────────
  {
    id: 21,
    title: 'VACUUM Breaking Time Travel',
    description: 'VACUUM with short retention breaks time travel',
    scenario: 'VACUUM RETAIN 0 HOURS run accidentally; history lost',
    impact: 'Cannot time travel, rollback impossible',
    rootCause: 'spark.databricks.delta.retentionDurationCheck.enabled=false',
    solution: 'Never disable retention check, standard 7-day retention',
    tools: 'Delta VACUUM, delta.deletedFileRetentionDuration',
  },
  {
    id: 22,
    title: 'Concurrent MERGE Conflict',
    description: 'MERGE failing with ConcurrentAppendException',
    scenario: 'Two pipelines MERGEing same partition simultaneously',
    impact: 'Job failure, retry storm, data lag',
    rootCause: 'Concurrent writers to same partition without isolation',
    solution: 'Partition-level locking, sequential writes, optimistic concurrency',
    tools: 'Delta isolation level, MERGE best practices',
  },
  {
    id: 23,
    title: 'Checkpoint Corruption',
    description: 'Structured streaming checkpoint unreadable',
    scenario: 'Cluster terminated mid-commit; checkpoint metadata inconsistent',
    impact: 'Stream cannot restart, data loss risk',
    rootCause: 'Cluster crash during commit, incompatible version upgrade',
    solution: 'Clean checkpoint, replay from Kafka offset, backup checkpoints',
    tools: 'Checkpoint location, Kafka starting offsets',
  },
  {
    id: 24,
    title: 'Schema Drift in Streaming',
    description: 'Stream fails when new column appears upstream',
    scenario: 'Producer adds field without notifying consumers',
    impact: 'Stream crash, data gap until restart',
    rootCause: 'mergeSchema=false, strict schema enforcement',
    solution: 'Enable mergeSchema, schema evolution policy, schema contract',
    tools: 'cloudFiles.schemaEvolutionMode=addNewColumns',
  },
  {
    id: 25,
    title: 'Delta Table Lock Contention',
    description: 'Writers blocked waiting for metadata lock',
    scenario: 'OPTIMIZE running while writers trying to append',
    impact: 'Slow writes, timeout errors',
    rootCause: 'Long OPTIMIZE/VACUUM holding lock, concurrent writers',
    solution: 'Schedule OPTIMIZE during low-traffic, partition-level OPTIMIZE',
    tools: 'OPTIMIZE ZORDER, table properties',
  },
  {
    id: 26,
    title: 'Small Files Despite AutoOptimize',
    description: 'Small files accumulating even with autoOptimize=true',
    scenario: 'Streaming micro-batch too small; autoOptimize cannot compact fast enough',
    impact: 'Read performance degradation',
    rootCause: 'Trigger interval too short, autoOptimize throttled',
    solution: 'Larger trigger intervals, schedule OPTIMIZE, increase maxFileSize',
    tools: 'delta.autoOptimize.autoCompact, targetFileSize',
  },
  {
    id: 27,
    title: '_delta_log Explosion',
    description: 'Delta log directory has 100K+ files',
    scenario: 'High-frequency writes without checkpointing; retention too long',
    impact: 'Slow table ops, listing timeouts',
    rootCause: 'No log compaction, infrequent checkpoints',
    solution: 'Set delta.logRetentionDuration, checkpoint frequency, OPTIMIZE',
    tools: 'delta.checkpointInterval, VACUUM log files',
  },
  {
    id: 28,
    title: 'Liquid Clustering Not Reducing Scan',
    description: 'Liquid clustering enabled but scans still reading all files',
    scenario: 'Clustering columns mismatch query filter pattern',
    impact: 'No performance improvement, OPTIMIZE cost wasted',
    rootCause: 'Wrong clustering keys, clustering not applied to old data',
    solution: 'Match clustering keys to common filters, OPTIMIZE FULL',
    tools: 'CLUSTER BY, OPTIMIZE FULL on existing tables',
  },
  {
    id: 29,
    title: 'Concurrent DELETE Fails',
    description: 'DELETE operations conflicting with writes',
    scenario: 'GDPR right-to-erasure DELETE while daily MERGE running',
    impact: 'One operation fails, compliance delay',
    rootCause: 'Optimistic concurrency conflict',
    solution: 'Schedule DELETE in window, use Deletion Vectors for faster ops',
    tools: 'Delta Deletion Vectors, merge scheduling',
  },
  {
    id: 30,
    title: 'OPTIMIZE Runtime > Ingest Interval',
    description: 'OPTIMIZE taking longer than new data arrival',
    scenario: 'Hourly OPTIMIZE unable to finish before next hour',
    impact: 'Small files accumulate, read slowdown',
    rootCause: 'Table too large, OPTIMIZE not incremental',
    solution: 'Partition-scoped OPTIMIZE, Liquid Clustering, larger cluster',
    tools: 'OPTIMIZE <table> WHERE partition_col=X',
  },

  // ── SQL Warehouse / BI (31-35) ──────────────────────────────────────
  {
    id: 31,
    title: 'Queries Queued — Slow BI',
    description: 'Power BI dashboard timing out; queries queued',
    scenario: 'SQL warehouse autoscale too slow for morning peak',
    impact: 'Executive dashboard unusable 9-10am',
    rootCause: 'min_clusters=1, slow scale-up, no warm pool',
    solution: 'Increase min_clusters, enable Serverless SQL, warm pool',
    tools: 'SQL warehouse config, Serverless SQL auto-scaling',
  },
  {
    id: 32,
    title: 'Photon Slower Than Classic',
    description: 'Photon-enabled query slower than classic runtime',
    scenario: 'Heavy UDF workload; Photon falls back to classic with overhead',
    impact: 'Unexpected cost increase, no perf gain',
    rootCause: 'Python UDFs, unsupported operations forcing fallback',
    solution: 'Replace UDFs with built-in, pandas UDF, Scala UDF',
    tools: 'EXPLAIN, Photon-compatible ops documentation',
  },
  {
    id: 33,
    title: 'Result Cache Miss',
    description: 'Identical query re-running despite cache',
    scenario: 'Underlying table updated every 5min invalidating cache',
    impact: 'Higher cost, slower dashboards',
    rootCause: 'Frequent writes invalidating cache, cache size too small',
    solution: 'Materialized views, scheduled refresh, query tuning',
    tools: 'SQL warehouse result cache, materialized views',
  },
  {
    id: 34,
    title: 'Materialized View Refresh Failing',
    description: 'MV stuck with refresh error',
    scenario: 'MV references upstream table that got schema change',
    impact: 'Stale data in reports',
    rootCause: 'Schema drift, permission issue, source unavailable',
    solution: 'Rebuild MV, add error notification, schema contract',
    tools: 'CREATE OR REPLACE MATERIALIZED VIEW',
  },
  {
    id: 35,
    title: 'Dashboard Data Mismatch',
    description: 'Same metric different across dashboards',
    scenario: 'Two dashboards with different WHERE clauses but same name',
    impact: 'Executive distrust, investigation burden',
    rootCause: 'No semantic layer, ad-hoc SQL everywhere',
    solution: 'Databricks metric views, certified Gold tables',
    tools: 'Metric views, dbt semantic layer',
  },

  // ── Streaming / Auto Loader (36-40) ─────────────────────────────────
  {
    id: 36,
    title: 'Streaming Checkpoint Incompatible',
    description: 'Version upgrade breaks streaming checkpoint',
    scenario: 'DBR upgrade changing serialization format',
    impact: 'Cannot restart stream, data loss',
    rootCause: 'DBR major version upgrade without migration',
    solution: 'Test upgrades in dev, clean checkpoint strategy, backup',
    tools: 'DBR version pinning, checkpoint migration guide',
  },
  {
    id: 37,
    title: 'Kafka Offset Reset',
    description: 'Stream starting from earliest, re-reading months of data',
    scenario: 'Consumer group reset; startingOffsets=earliest by default',
    impact: 'Huge backlog, hours of reprocessing',
    rootCause: 'startingOffsets not explicit, group offsets deleted',
    solution: 'Explicit startingOffsets with saved offsets, backup offsets',
    tools: 'Kafka startingOffsets option, offset management',
  },
  {
    id: 38,
    title: 'Auto Loader Skipping Files',
    description: 'Files in source path not showing in target',
    scenario: 'cloudFiles using notifications; SQS queue misconfigured',
    impact: 'Missing data, reconciliation mismatch',
    rootCause: 'Notification mode misconfigured, SQS permission, file path issue',
    solution: 'Switch to directory listing mode, verify SQS/Event Grid',
    tools: 'cloudFiles.useNotifications, cloudFiles.backfillInterval',
  },
  {
    id: 39,
    title: 'Streaming Backlog Growing',
    description: 'Input rate > processing rate; lag increasing',
    scenario: 'Promo event spiking event volume 10x',
    impact: 'SLA breach, downstream latency',
    rootCause: 'Insufficient parallelism, backpressure, slow sink',
    solution: 'Increase maxFilesPerTrigger, more cores, optimize sink',
    tools: 'Structured Streaming metrics, trigger tuning',
  },
  {
    id: 40,
    title: 'Foreach Sink Error',
    description: 'foreachBatch throwing exception on some batches',
    scenario: 'External API in sink throwing 500 intermittently',
    impact: 'Stream crashes on single batch failure',
    rootCause: 'No error handling in foreachBatch, external service instability',
    solution: 'Wrap in try/catch, dead-letter queue, retry with backoff',
    tools: 'foreachBatch error handling, DLT for resilient streams',
  },

  // ── Unity Catalog / Governance (41-45) ──────────────────────────────
  {
    id: 41,
    title: 'UC Metastore Region Mismatch',
    description: 'Cannot access catalog from different region workspace',
    scenario: 'Workspace in us-east-1, metastore in us-west-2',
    impact: 'Cross-region latency, access failures',
    rootCause: 'UC metastore is region-scoped',
    solution: 'One metastore per region, federated catalog pattern',
    tools: 'UC metastore regional design',
  },
  {
    id: 42,
    title: 'External Location Access Failure',
    description: 'Cannot read from external storage',
    scenario: 'Storage credential IAM role revoked',
    impact: 'All external tables inaccessible',
    rootCause: 'IAM role deleted, trust relationship broken',
    solution: 'Automated credential rotation, monitoring, backup credential',
    tools: 'UC storage credentials, IAM role audit',
  },
  {
    id: 43,
    title: 'Storage Credential Expired',
    description: 'Service principal secret expired',
    scenario: 'Azure AD secret rotation without UC update',
    impact: 'All UC external tables fail',
    rootCause: 'Manual secret rotation not propagated to UC',
    solution: 'Use managed identity instead, automated rotation pipeline',
    tools: 'UC managed identity, Azure AD secret rotation',
  },
  {
    id: 44,
    title: 'Shallow Clone Broken',
    description: 'Clone target missing after source VACUUM',
    scenario: 'Source table VACUUMed; shallow clone lost parquet files',
    impact: 'Cloned table unusable',
    rootCause: 'Shallow clone shares data files; source VACUUM deleted them',
    solution: 'Use DEEP CLONE for independence, VACUUM carefully',
    tools: 'CREATE TABLE ... DEEP CLONE',
  },
  {
    id: 45,
    title: 'Delta Sharing Recipient Timeout',
    description: 'External recipient cannot read shared table',
    scenario: 'Recipient network blocking Databricks endpoints',
    impact: 'Partner cannot consume data',
    rootCause: 'Firewall blocking Databricks CDN, expired token',
    solution: 'Whitelist Databricks endpoints, rotate recipient tokens',
    tools: 'Delta Sharing recipient tokens, IP allowlist',
  },

  // ── Cost / Platform (46-50) ─────────────────────────────────────────
  {
    id: 46,
    title: 'Surprise Bill — All-Purpose Abuse',
    description: 'Monthly bill 5x expected',
    scenario: 'Team using All-Purpose cluster 24/7 for scheduled jobs',
    impact: 'Budget blown, finance escalation',
    rootCause: 'No cluster policy enforcing Job clusters for schedules',
    solution: 'Cluster policies, auto-termination, tagging + chargeback',
    tools: 'Cluster policies, system.billing.usage, tags',
  },
  {
    id: 47,
    title: 'GPU Cluster Idle Cost',
    description: 'GPU cluster costing $500/day idle',
    scenario: 'Data scientist left GPU cluster running over weekend',
    impact: 'Hundreds of dollars wasted per incident',
    rootCause: 'No auto-termination on GPU clusters, no alerts',
    solution: 'Aggressive auto-termination, cost alerts, serverless inference',
    tools: 'Cluster auto-termination, cost dashboards',
  },
  {
    id: 48,
    title: 'Serverless SQL Overshoot',
    description: 'Serverless SQL scaled to max, cost 10x expected',
    scenario: 'Bad query with cross-join triggered autoscale spike',
    impact: 'Budget blown in one query',
    rootCause: 'No query size limits, runaway query',
    solution: 'Statement timeout, query limits, cost alerts per warehouse',
    tools: 'SQL warehouse max_clusters, statement timeout',
  },
  {
    id: 49,
    title: 'Workspace Quota Hit',
    description: 'Cannot create new cluster — quota reached',
    scenario: 'Too many active clusters in workspace exceeding soft quota',
    impact: 'New jobs cannot start, operational block',
    rootCause: 'No cleanup of stale clusters, quota too low for workload',
    solution: 'Cleanup scripts, quota increase request, multi-workspace strategy',
    tools: 'Databricks workspace quotas API, cleanup automation',
  },
  {
    id: 50,
    title: 'Log4j / Security Patch Force Restart',
    description: 'Emergency security patch forcing all clusters to restart',
    scenario: 'CVE disclosure; Databricks forces DBR runtime update',
    impact: 'All running jobs terminated mid-execution',
    rootCause: 'Critical security patch timing',
    solution: 'Subscribe to security alerts, idempotent jobs, rapid patch strategy',
    tools: 'Databricks runtime advisories, cluster policy version management',
  },
];

export default function DatabricksProductionIssues() {
  return (
    <ChallengeLibrary
      pageTitle="Databricks Production Issues — 50 Real-World Failures"
      pageSubtitle="Cluster, jobs, Delta, SQL warehouse, streaming, Unity Catalog, cost — every issue has real scenario, impact, root cause, resolution, and architect-level action sequence."
      statsLabel="Production Issues"
      totalCount={50}
      challenges={CHALLENGES}
      domain="observability"
      csvName="databricks-production-issues.csv"
    />
  );
}
