import React from 'react';
import ImplementationLibrary from '../../components/architect/ImplementationLibrary';

const ROWS = [
  {
    id: 1,
    topic: 'Security Strategy',
    definition: 'Define enterprise security framework',
    implementation: 'Align with Zero Trust + least privilege',
    task: 'Define security policies',
    service: 'Databricks + Cloud IAM',
    deliverable: 'Security strategy doc',
    validation: 'Stakeholder validation',
    testing: 'Policy tests',
    comparison: 'Ad-hoc vs Zero Trust',
    deployment: 'Phased rollout',
    flow: 'Org → Security',
  },
  {
    id: 2,
    topic: 'Identity & Access Management (IAM)',
    definition: 'Control user/service identity',
    implementation: 'Integrate Azure AD / AWS IAM',
    task: 'Manage users, groups, service principals',
    service: 'IAM',
    deliverable: 'IAM config',
    validation: 'Access validation',
    testing: 'Auth tests',
    comparison: 'Local users vs centralized IAM',
    deployment: 'Org-wide deployment',
    flow: 'User → Identity',
  },
  {
    id: 3,
    topic: 'Authentication',
    definition: 'Verify user identity',
    implementation: 'Enable SSO, MFA',
    task: 'Secure login flow',
    service: 'Azure AD / Okta',
    deliverable: 'Auth setup',
    validation: 'Login validation',
    testing: 'MFA tests',
    comparison: 'Password-only vs MFA',
    deployment: 'Org rollout',
    flow: 'User → Auth',
  },
  {
    id: 4,
    topic: 'Authorization (RBAC)',
    definition: 'Control access permissions',
    implementation: 'Define roles, grant privileges',
    task: 'Apply least privilege',
    service: 'Unity Catalog',
    deliverable: 'Access policy',
    validation: 'Permission validation',
    testing: 'Access tests',
    comparison: 'Open vs RBAC',
    deployment: 'Policy rollout',
    flow: 'Identity → Access',
  },
  {
    id: 5,
    topic: 'Fine-Grained Access Control',
    definition: 'Control at table/column/row level',
    implementation: 'Apply RLS, CLS policies',
    task: 'Restrict sensitive data',
    service: 'Unity Catalog',
    deliverable: 'Fine-grained policies',
    validation: 'Access validation',
    testing: 'Security tests',
    comparison: 'Coarse vs fine-grained',
    deployment: 'Policy deployment',
    flow: 'Role → Data',
  },
  {
    id: 6,
    topic: 'Data Encryption (At Rest)',
    definition: 'Protect stored data',
    implementation: 'Enable encryption in storage (ADLS/S3)',
    task: 'Configure KMS keys',
    service: 'Cloud storage',
    deliverable: 'Encrypted data',
    validation: 'Encryption validation',
    testing: 'Security tests',
    comparison: 'Plain vs encrypted',
    deployment: 'Auto-enabled',
    flow: 'Data → Secure',
  },
  {
    id: 7,
    topic: 'Data Encryption (In Transit)',
    definition: 'Protect data in motion',
    implementation: 'Use TLS/HTTPS for all communication',
    task: 'Enforce secure channels',
    service: 'Network layer',
    deliverable: 'Secure communication',
    validation: 'SSL validation',
    testing: 'Network tests',
    comparison: 'HTTP vs HTTPS',
    deployment: 'Default enforcement',
    flow: 'Data → Transfer',
  },
  {
    id: 8,
    topic: 'Secrets Management',
    definition: 'Secure credentials',
    implementation: 'Store secrets in vault',
    task: 'Avoid hardcoding',
    service: 'Azure Key Vault / AWS Secrets',
    deliverable: 'Secret store',
    validation: 'Access validation',
    testing: 'Security tests',
    comparison: 'Hardcoded vs vault',
    deployment: 'Vault integration',
    flow: 'Secret → Access',
  },
  {
    id: 9,
    topic: 'Network Security',
    definition: 'Protect network boundaries',
    implementation: 'Use VNet/VPC, private endpoints',
    task: 'Restrict public access',
    service: 'Cloud networking',
    deliverable: 'Network config',
    validation: 'Network validation',
    testing: 'Pen test',
    comparison: 'Open vs private network',
    deployment: 'Infra deployment',
    flow: 'Network → Secure',
  },
  {
    id: 10,
    topic: 'IP Access Control',
    definition: 'Restrict access by IP',
    implementation: 'Whitelist trusted IPs',
    task: 'Prevent unauthorized access',
    service: 'Databricks',
    deliverable: 'IP access list',
    validation: 'Access validation',
    testing: 'Security test',
    comparison: 'Open vs restricted IP',
    deployment: 'Policy rollout',
    flow: 'IP → Access',
  },
  {
    id: 11,
    topic: 'Secure Cluster Configuration',
    definition: 'Harden compute environment',
    implementation: 'Use secure cluster policies',
    task: 'Restrict configs and libraries',
    service: 'Databricks',
    deliverable: 'Cluster policy',
    validation: 'Policy validation',
    testing: 'Config tests',
    comparison: 'Open vs hardened cluster',
    deployment: 'Policy deployment',
    flow: 'Cluster → Secure',
  },
  {
    id: 12,
    topic: 'Credential Passthrough',
    definition: 'Secure data access via identity',
    implementation: 'Enable user identity propagation',
    task: 'Avoid shared credentials',
    service: 'Databricks + IAM',
    deliverable: 'Secure access model',
    validation: 'Access validation',
    testing: 'Auth tests',
    comparison: 'Shared vs identity-based',
    deployment: 'Config rollout',
    flow: 'User → Data',
  },
  {
    id: 13,
    topic: 'Data Masking',
    definition: 'Protect sensitive fields',
    implementation: 'Mask/tokenize PII data',
    task: 'Apply masking policies',
    service: 'Unity Catalog',
    deliverable: 'Masked data',
    validation: 'Mask validation',
    testing: 'Security tests',
    comparison: 'Raw vs masked',
    deployment: 'Policy rollout',
    flow: 'Data → Mask',
  },
  {
    id: 14,
    topic: 'Tokenization',
    definition: 'Replace sensitive values',
    implementation: 'Tokenize PII fields',
    task: 'Prevent exposure',
    service: 'Security tools',
    deliverable: 'Tokenized data',
    validation: 'Token validation',
    testing: 'Security tests',
    comparison: 'Plain vs tokenized',
    deployment: 'Pipeline integration',
    flow: 'Data → Token',
  },
  {
    id: 15,
    topic: 'Audit Logging',
    definition: 'Track access and activity',
    implementation: 'Log queries, access, changes',
    task: 'Enable audit trail',
    service: 'Databricks / Cloud logs',
    deliverable: 'Audit logs',
    validation: 'Log validation',
    testing: 'Audit tests',
    comparison: 'No logs vs full audit',
    deployment: 'Central logging',
    flow: 'Activity → Log',
  },
  {
    id: 16,
    topic: 'Monitoring & Alerting',
    definition: 'Detect security issues',
    implementation: 'Monitor anomalies, access patterns',
    task: 'Configure alerts',
    service: 'SIEM / Datadog',
    deliverable: 'Security dashboard',
    validation: 'Alert validation',
    testing: 'Alert tests',
    comparison: 'Reactive vs proactive',
    deployment: 'Continuous monitoring',
    flow: 'Logs → Alerts',
  },
  {
    id: 17,
    topic: 'Threat Detection',
    definition: 'Identify malicious activity',
    implementation: 'Use anomaly detection and SIEM tools',
    task: 'Detect breaches',
    service: 'SIEM tools',
    deliverable: 'Threat report',
    validation: 'Detection validation',
    testing: 'Security tests',
    comparison: 'No detection vs active monitoring',
    deployment: 'Continuous monitoring',
    flow: 'Threat → Alert',
  },
  {
    id: 18,
    topic: 'Data Loss Prevention (DLP)',
    definition: 'Prevent data leakage',
    implementation: 'Apply DLP rules and scanning',
    task: 'Detect sensitive data movement',
    service: 'DLP tools',
    deliverable: 'DLP policy',
    validation: 'DLP validation',
    testing: 'Security tests',
    comparison: 'No DLP vs controlled',
    deployment: 'Policy rollout',
    flow: 'Data → Protected',
  },
  {
    id: 19,
    topic: 'API Security',
    definition: 'Secure AI/data APIs',
    implementation: 'Use authentication, rate limiting',
    task: 'Protect endpoints',
    service: 'API Gateway',
    deliverable: 'Secure API',
    validation: 'API validation',
    testing: 'Load + security tests',
    comparison: 'Open vs secured API',
    deployment: 'API deployment',
    flow: 'User → API',
  },
  {
    id: 20,
    topic: 'AI Security (Prompt Injection)',
    definition: 'Protect AI systems',
    implementation: 'Filter malicious prompts',
    task: 'Apply guardrails',
    service: 'LLM tools',
    deliverable: 'Secure AI system',
    validation: 'Input validation',
    testing: 'Adversarial tests',
    comparison: 'Open vs guarded AI',
    deployment: 'Policy deployment',
    flow: 'Input → Filter',
  },
  {
    id: 21,
    topic: 'Data Privacy',
    definition: 'Protect personal data',
    implementation: 'Apply PII masking, consent controls',
    task: 'Ensure compliance',
    service: 'Governance tools',
    deliverable: 'Privacy-compliant system',
    validation: 'Privacy validation',
    testing: 'Compliance tests',
    comparison: 'Raw vs protected data',
    deployment: 'Policy rollout',
    flow: 'Data → Privacy',
  },
  {
    id: 22,
    topic: 'Compliance (GDPR/HIPAA)',
    definition: 'Meet regulatory standards',
    implementation: 'Implement audit, retention, masking',
    task: 'Ensure compliance readiness',
    service: 'Governance tools',
    deliverable: 'Compliance report',
    validation: 'Audit validation',
    testing: 'Compliance tests',
    comparison: 'Non-compliant vs compliant',
    deployment: 'Policy rollout',
    flow: 'Data → Compliance',
  },
  {
    id: 23,
    topic: 'Backup & Recovery',
    definition: 'Protect against data loss',
    implementation: 'Implement backup and restore strategy',
    task: 'Ensure availability',
    service: 'Storage + Databricks',
    deliverable: 'Backup system',
    validation: 'Recovery validation',
    testing: 'DR tests',
    comparison: 'No backup vs resilient',
    deployment: 'Scheduled jobs',
    flow: 'Data → Backup',
  },
  {
    id: 24,
    topic: 'Disaster Recovery (DR)',
    definition: 'Ensure system resilience',
    implementation: 'Multi-region failover setup',
    task: 'Enable recovery plan',
    service: 'Cloud infra',
    deliverable: 'DR plan',
    validation: 'Failover validation',
    testing: 'DR tests',
    comparison: 'Single region vs DR-ready',
    deployment: 'Deployment',
    flow: 'Region → Failover',
  },
  {
    id: 25,
    topic: 'Vulnerability Management',
    definition: 'Identify system weaknesses',
    implementation: 'Scan clusters, dependencies',
    task: 'Fix vulnerabilities',
    service: 'Security tools',
    deliverable: 'Vulnerability report',
    validation: 'Scan validation',
    testing: 'Security tests',
    comparison: 'Unscanned vs secured',
    deployment: 'Continuous scanning',
    flow: 'System → Secure',
  },
  {
    id: 26,
    topic: 'Patch Management',
    definition: 'Keep system updated',
    implementation: 'Apply updates to clusters/libs',
    task: 'Reduce risk',
    service: 'Databricks / OS',
    deliverable: 'Patch log',
    validation: 'Patch validation',
    testing: 'Regression tests',
    comparison: 'Outdated vs patched',
    deployment: 'Scheduled updates',
    flow: 'System → Update',
  },
  {
    id: 27,
    topic: 'Security Testing',
    definition: 'Validate security controls',
    implementation: 'Perform penetration and vulnerability testing',
    task: 'Ensure system security',
    service: 'QA / Security tools',
    deliverable: 'Security test report',
    validation: 'Test validation',
    testing: 'Pen tests',
    comparison: 'Untested vs secure',
    deployment: 'Release gating',
    flow: 'System → Test',
  },
  {
    id: 28,
    topic: 'DevSecOps',
    definition: 'Integrate security in CI/CD',
    implementation: 'Scan code, dependencies, configs',
    task: 'Automate security checks',
    service: 'GitHub / DevOps',
    deliverable: 'Secure pipeline',
    validation: 'Build validation',
    testing: 'Security tests',
    comparison: 'DevOps vs DevSecOps',
    deployment: 'CI/CD deploy',
    flow: 'Code → Secure',
  },
  {
    id: 29,
    topic: 'Multi-Cloud Security',
    definition: 'Secure across Azure/AWS/GCP',
    implementation: 'Standardize policies across clouds',
    task: 'Ensure consistency',
    service: 'Cloud tools',
    deliverable: 'Unified security model',
    validation: 'Cross-cloud validation',
    testing: 'Integration tests',
    comparison: 'Isolated vs unified',
    deployment: 'Policy sync',
    flow: 'Multi-cloud → Secure',
  },
  {
    id: 30,
    topic: 'Security Governance',
    definition: 'Manage security policies',
    implementation: 'Define roles, audits, compliance tracking',
    task: 'Maintain governance',
    service: 'Governance tools',
    deliverable: 'Security governance framework',
    validation: 'Governance validation',
    testing: 'Audit tests',
    comparison: 'Ad-hoc vs governed',
    deployment: 'Continuous monitoring',
    flow: 'Security → Governance',
  },
];

export default function DataAISecurity() {
  return (
    <ImplementationLibrary
      pageTitle="Data + AI Security — Enterprise Implementation"
      pageSubtitle="30 security patterns covering Zero Trust, IAM, encryption, DLP, AI security (prompt injection), DevSecOps, and compliance."
      statsLabel="Security Topics"
      rows={ROWS}
      csvName="data-ai-security-implementation.csv"
      accent="#ef4444"
    />
  );
}
