import React from 'react';
import ChallengeLibrary from '../../components/architect/ChallengeLibrary';

const CHALLENGES = [
  {
    id: 1,
    title: 'Data Ownership',
    description: 'No clear data owner',
    scenario: 'Customer data issues unresolved',
    impact: 'No accountability',
    rootCause: 'No ownership model',
    solution: 'Define data owners/stewards',
    tools: 'Unity Catalog',
  },
  {
    id: 2,
    title: 'Data Classification',
    description: 'Data not classified (PII, sensitive)',
    scenario: 'PII exposed in reports',
    impact: 'Compliance risk',
    rootCause: 'No classification policy',
    solution: 'Data classification framework',
    tools: 'UC, Collibra',
  },
  {
    id: 3,
    title: 'Access Control',
    description: 'No RBAC/ABAC',
    scenario: 'Everyone accesses all data',
    impact: 'Security breach',
    rootCause: 'Weak IAM',
    solution: 'Role-based access control',
    tools: 'Unity Catalog',
  },
  {
    id: 4,
    title: 'Fine-Grained Security',
    description: 'No row/column-level security',
    scenario: 'Sensitive fields visible',
    impact: 'Privacy issue',
    rootCause: 'Coarse access control',
    solution: 'Row/column masking',
    tools: 'Unity Catalog',
  },
  {
    id: 5,
    title: 'Data Lineage',
    description: 'No end-to-end lineage',
    scenario: 'Cannot trace data source',
    impact: 'Debug failure',
    rootCause: 'No lineage system',
    solution: 'Enable lineage tracking',
    tools: 'Unity Catalog',
  },
  {
    id: 6,
    title: 'Metadata Management',
    description: 'No metadata catalog',
    scenario: 'Tables undocumented',
    impact: 'Low usability',
    rootCause: 'No catalog',
    solution: 'Central metadata system',
    tools: 'Collibra, UC',
  },
  {
    id: 7,
    title: 'Data Quality Governance',
    description: 'No quality standards',
    scenario: 'Bad data used in reports',
    impact: 'Wrong decisions',
    rootCause: 'No validation rules',
    solution: 'Data quality framework',
    tools: 'Great Expectations',
  },
  {
    id: 8,
    title: 'Policy Enforcement',
    description: 'Policies exist but not enforced',
    scenario: 'Teams bypass rules',
    impact: 'Inconsistency',
    rootCause: 'No policy-as-code',
    solution: 'Automated policy enforcement',
    tools: 'Azure Policy, OPA',
  },
  {
    id: 9,
    title: 'Audit Logging',
    description: 'No audit trail',
    scenario: 'Cannot track who accessed data',
    impact: 'Audit failure',
    rootCause: 'No logging',
    solution: 'Enable audit logs',
    tools: 'UC, Cloud logs',
  },
  {
    id: 10,
    title: 'Compliance',
    description: 'No regulatory alignment',
    scenario: 'GDPR/PII violation',
    impact: 'Legal risk',
    rootCause: 'No compliance mapping',
    solution: 'Compliance framework',
    tools: 'GRC tools',
  },
  {
    id: 11,
    title: 'Data Retention',
    description: 'No retention policy',
    scenario: 'Old data stored forever',
    impact: 'Cost + compliance risk',
    rootCause: 'No lifecycle rules',
    solution: 'Data retention policies',
    tools: 'Storage lifecycle',
  },
  {
    id: 12,
    title: 'Data Deletion',
    description: 'Cannot delete data properly',
    scenario: 'Right to be forgotten not met',
    impact: 'Legal issue',
    rootCause: 'No deletion process',
    solution: 'Data deletion workflow',
    tools: 'Governance tools',
  },
  {
    id: 13,
    title: 'Data Masking',
    description: 'Sensitive data not masked',
    scenario: 'SSN visible in raw data',
    impact: 'Security risk',
    rootCause: 'No masking policy',
    solution: 'Dynamic masking',
    tools: 'Unity Catalog',
  },
  {
    id: 14,
    title: 'Data Sharing',
    description: 'Unsafe data sharing',
    scenario: 'Data shared externally without control',
    impact: 'Breach risk',
    rootCause: 'No sharing policy',
    solution: 'Secure data sharing',
    tools: 'Delta Sharing',
  },
  {
    id: 15,
    title: 'Multi-Cloud Governance',
    description: 'Different rules across cloud',
    scenario: 'Azure vs AWS mismatch',
    impact: 'Governance gap',
    rootCause: 'No unified governance',
    solution: 'Central governance framework',
    tools: 'UC + GRC',
  },
  {
    id: 16,
    title: 'Data Catalog Adoption',
    description: 'Catalog exists but unused',
    scenario: 'Users bypass catalog',
    impact: 'Low adoption',
    rootCause: 'Poor UX/training',
    solution: 'Improve adoption strategy',
    tools: 'Collibra',
  },
  {
    id: 17,
    title: 'Business Glossary',
    description: 'No standard definitions',
    scenario: 'Revenue defined differently',
    impact: 'Confusion',
    rootCause: 'No glossary',
    solution: 'Business glossary',
    tools: 'Collibra',
  },
  {
    id: 18,
    title: 'Data Stewardship',
    description: 'No data steward role',
    scenario: 'Data quality not managed',
    impact: 'Poor data trust',
    rootCause: 'No stewardship model',
    solution: 'Assign stewards',
    tools: 'Governance model',
  },
  {
    id: 19,
    title: 'Data Contracts',
    description: 'No schema/data contracts',
    scenario: 'Upstream changes break pipeline',
    impact: 'Failure',
    rootCause: 'No contract system',
    solution: 'Data contracts',
    tools: 'Schema registry',
  },
  {
    id: 20,
    title: 'Schema Governance',
    description: 'Schema changes unmanaged',
    scenario: 'Column added breaks jobs',
    impact: 'Pipeline failure',
    rootCause: 'No schema control',
    solution: 'Schema governance',
    tools: 'Delta Lake',
  },
  {
    id: 21,
    title: 'Data Access Requests',
    description: 'Manual access process',
    scenario: 'Slow onboarding',
    impact: 'Delay',
    rootCause: 'No automation',
    solution: 'Access workflow automation',
    tools: 'IAM tools',
  },
  {
    id: 22,
    title: 'Data Encryption',
    description: 'Data not encrypted',
    scenario: 'Data exposed',
    impact: 'Security risk',
    rootCause: 'No encryption standard',
    solution: 'Encryption at rest/in transit',
    tools: 'KMS',
  },
  {
    id: 23,
    title: 'Key Management',
    description: 'Poor key handling',
    scenario: 'Keys leaked',
    impact: 'Security breach',
    rootCause: 'No key rotation',
    solution: 'Key management policy',
    tools: 'Key Vault',
  },
  {
    id: 24,
    title: 'Data Isolation',
    description: 'No environment separation',
    scenario: 'Dev accesses prod data',
    impact: 'Risk',
    rootCause: 'No isolation',
    solution: 'Environment segregation',
    tools: 'Landing zones',
  },
  {
    id: 25,
    title: 'Shadow Data',
    description: 'Unauthorized datasets',
    scenario: 'Teams create hidden datasets',
    impact: 'Governance gap',
    rootCause: 'No control',
    solution: 'Data discovery tools',
    tools: 'Catalog tools',
  },
  {
    id: 26,
    title: 'Data Duplication Governance',
    description: 'Same data in multiple places',
    scenario: 'Multiple versions of truth',
    impact: 'Inconsistency',
    rootCause: 'No governance',
    solution: 'Single source of truth',
    tools: 'Lakehouse',
  },
  {
    id: 27,
    title: 'Data Usage Monitoring',
    description: 'No tracking of usage',
    scenario: 'Unknown who uses data',
    impact: 'Risk',
    rootCause: 'No monitoring',
    solution: 'Usage analytics',
    tools: 'UC, logs',
  },
  {
    id: 28,
    title: 'Data Drift Governance',
    description: 'Data changes unnoticed',
    scenario: 'Data pattern shifts',
    impact: 'Poor analytics',
    rootCause: 'No monitoring',
    solution: 'Drift detection',
    tools: 'Monitoring tools',
  },
  {
    id: 29,
    title: 'Data Lifecycle Governance',
    description: 'No lifecycle tracking',
    scenario: 'Data not archived',
    impact: 'Cost issue',
    rootCause: 'No lifecycle mgmt',
    solution: 'Lifecycle automation',
    tools: 'Storage policies',
  },
  {
    id: 30,
    title: 'Data Approval Workflow',
    description: 'No approval before publishing',
    scenario: 'Wrong dataset published',
    impact: 'Risk',
    rootCause: 'No workflow',
    solution: 'Data approval process',
    tools: 'Governance tools',
  },
  {
    id: 31,
    title: 'External Data Governance',
    description: 'Third-party data not validated',
    scenario: 'Vendor data unreliable',
    impact: 'Risk',
    rootCause: 'No validation',
    solution: 'External data validation',
    tools: 'ETL tools',
  },
  {
    id: 32,
    title: 'Data Ethics',
    description: 'Data used unethically',
    scenario: 'Bias in dataset',
    impact: 'Ethical risk',
    rootCause: 'No ethical policy',
    solution: 'Ethical AI framework',
    tools: 'ISO 42001',
  },
  {
    id: 33,
    title: 'Data Compliance Audit',
    description: 'No audit readiness',
    scenario: 'Audit fails',
    impact: 'Penalty',
    rootCause: 'No audit evidence',
    solution: 'Audit framework',
    tools: 'GRC tools',
  },
  {
    id: 34,
    title: 'Data Versioning',
    description: 'No dataset versioning',
    scenario: 'Cannot track changes',
    impact: 'Debug issues',
    rootCause: 'No versioning',
    solution: 'Data version control',
    tools: 'Delta Lake',
  },
  {
    id: 35,
    title: 'Data Reconciliation',
    description: 'No validation vs source',
    scenario: 'Data mismatch',
    impact: 'Trust issue',
    rootCause: 'No reconciliation',
    solution: 'Reconciliation process',
    tools: 'Spark',
  },
  {
    id: 36,
    title: 'Data Ownership Conflict',
    description: 'Multiple owners',
    scenario: 'Conflict in decisions',
    impact: 'Delay',
    rootCause: 'Poor governance',
    solution: 'Clear ownership model',
    tools: 'RACI',
  },
  {
    id: 37,
    title: 'Data Security Monitoring',
    description: 'No monitoring for breaches',
    scenario: 'Unauthorized access unnoticed',
    impact: 'Risk',
    rootCause: 'No monitoring',
    solution: 'Security monitoring',
    tools: 'SIEM',
  },
  {
    id: 38,
    title: 'Data Governance Automation',
    description: 'Manual governance processes',
    scenario: 'Slow operations',
    impact: 'Inefficiency',
    rootCause: 'No automation',
    solution: 'Automated governance',
    tools: 'Policy engines',
  },
  {
    id: 39,
    title: 'AI Data Governance',
    description: 'No governance for AI data',
    scenario: 'Training data uncontrolled',
    impact: 'AI risk',
    rootCause: 'No AI governance',
    solution: 'AI data governance model',
    tools: 'MLflow + UC',
  },
  {
    id: 40,
    title: 'Data Trust',
    description: 'Low trust in data',
    scenario: 'Business rejects dashboards',
    impact: 'Low adoption',
    rootCause: 'Poor governance',
    solution: 'Data trust framework',
    tools: 'Governance tools',
  },
];

function GovernanceChallenges() {
  return (
    <ChallengeLibrary
      pageTitle="Data Governance — 40 Challenges"
      pageSubtitle="Enterprise governance challenges (ownership, lineage, policy, compliance) with architect-level playbooks."
      statsLabel="Governance Challenges"
      totalCount={40}
      challenges={CHALLENGES}
      domain="governance"
      csvName="governance-challenges.csv"
    />
  );
}

export default GovernanceChallenges;
