import React from 'react';
import ImplementationLibrary from '../../components/architect/ImplementationLibrary';

const ROWS = [
  {
    id: 1,
    topic: 'Governance Strategy',
    definition: 'Define governance framework',
    implementation: 'Establish policies, roles, standards',
    task: 'Align business + IT',
    service: 'Unity Catalog',
    deliverable: 'Governance strategy doc',
    validation: 'Stakeholder approval',
    testing: 'Policy validation',
    comparison: 'Ad-hoc vs governed',
    deployment: 'Controlled rollout',
    flow: 'Org → Governance',
  },
  {
    id: 2,
    topic: 'Data Classification',
    definition: 'Identify sensitive data',
    implementation: 'Tag PII, financial, confidential data',
    task: 'Apply classification tags',
    service: 'Unity Catalog',
    deliverable: 'Classified datasets',
    validation: 'Tag validation',
    testing: 'Classification tests',
    comparison: 'Unclassified vs classified',
    deployment: 'Metadata deployment',
    flow: 'Data → Classification',
  },
  {
    id: 3,
    topic: 'Catalog Management',
    definition: 'Central metadata repository',
    implementation: 'Register tables, schemas, owners',
    task: 'Maintain data catalog',
    service: 'Unity Catalog',
    deliverable: 'Data catalog',
    validation: 'Metadata completeness',
    testing: 'Catalog tests',
    comparison: 'No catalog vs centralized',
    deployment: 'Continuous update',
    flow: 'Data → Catalog',
  },
  {
    id: 4,
    topic: 'RBAC (Access Control)',
    definition: 'Role-based access management',
    implementation: 'Define roles, grant permissions',
    task: 'Implement least privilege',
    service: 'Unity Catalog / IAM',
    deliverable: 'Access policy',
    validation: 'Access validation',
    testing: 'Permission tests',
    comparison: 'Open vs restricted',
    deployment: 'Policy deployment',
    flow: 'User → Data access',
  },
  {
    id: 5,
    topic: 'Column-Level Security',
    definition: 'Protect sensitive columns',
    implementation: 'Mask PII fields',
    task: 'Apply masking policies',
    service: 'Unity Catalog',
    deliverable: 'Masked columns',
    validation: 'Mask validation',
    testing: 'Security tests',
    comparison: 'Raw vs masked data',
    deployment: 'Policy rollout',
    flow: 'Data → Masking',
  },
  {
    id: 6,
    topic: 'Row-Level Security',
    definition: 'Restrict data by context',
    implementation: 'Filter rows based on role/region',
    task: 'Implement row filters',
    service: 'Unity Catalog',
    deliverable: 'Filtered views',
    validation: 'Access validation',
    testing: 'RLS tests',
    comparison: 'Full vs filtered data',
    deployment: 'Controlled release',
    flow: 'Data → Filtered view',
  },
  {
    id: 7,
    topic: 'Data Lineage',
    definition: 'Track data flow',
    implementation: 'Enable table + column lineage',
    task: 'Capture transformation flow',
    service: 'Unity Catalog',
    deliverable: 'Lineage graph',
    validation: 'Lineage validation',
    testing: 'Audit tests',
    comparison: 'No lineage vs full lineage',
    deployment: 'Auto-enabled',
    flow: 'Source → BI',
  },
  {
    id: 8,
    topic: 'Data Quality Governance',
    definition: 'Enforce data quality standards',
    implementation: 'Define rules, thresholds, SLAs',
    task: 'Implement validation checks',
    service: 'dbt / Great Expectations',
    deliverable: 'DQ dashboards',
    validation: 'Threshold validation',
    testing: 'DQ tests',
    comparison: 'Reactive vs governed',
    deployment: 'Integrated pipeline',
    flow: 'Data → Quality',
  },
  {
    id: 9,
    topic: 'Data Ownership',
    definition: 'Assign accountability',
    implementation: 'Define data owners/stewards',
    task: 'Maintain ownership registry',
    service: 'Catalog tools',
    deliverable: 'Ownership mapping',
    validation: 'Owner validation',
    testing: 'Governance review',
    comparison: 'No owner vs owned data',
    deployment: 'Continuous update',
    flow: 'Data → Owner',
  },
  {
    id: 10,
    topic: 'Metadata Management',
    definition: 'Manage technical + business metadata',
    implementation: 'Store schema, lineage, KPI definitions',
    task: 'Maintain metadata lifecycle',
    service: 'Unity Catalog',
    deliverable: 'Metadata repository',
    validation: 'Metadata audit',
    testing: 'Metadata tests',
    comparison: 'Sparse vs rich metadata',
    deployment: 'Auto-capture',
    flow: 'Data → Metadata',
  },
  {
    id: 11,
    topic: 'Audit Logging',
    definition: 'Track data access and changes',
    implementation: 'Enable audit logs for queries/access',
    task: 'Store audit events',
    service: 'Databricks / Cloud logs',
    deliverable: 'Audit logs',
    validation: 'Log validation',
    testing: 'Audit tests',
    comparison: 'No audit vs full audit',
    deployment: 'Central logging',
    flow: 'Access → Audit',
  },
  {
    id: 12,
    topic: 'Compliance Management',
    definition: 'Ensure regulatory compliance',
    implementation: 'Map policies to GDPR, HIPAA, etc.',
    task: 'Enforce compliance controls',
    service: 'Governance tools',
    deliverable: 'Compliance report',
    validation: 'Regulatory validation',
    testing: 'Compliance tests',
    comparison: 'Non-compliant vs compliant',
    deployment: 'Policy rollout',
    flow: 'Data → Compliance',
  },
  {
    id: 13,
    topic: 'Data Retention Policy',
    definition: 'Manage data lifecycle',
    implementation: 'Define retention and purge rules',
    task: 'Implement retention jobs',
    service: 'Databricks / Storage',
    deliverable: 'Retention policy',
    validation: 'Retention validation',
    testing: 'Data aging tests',
    comparison: 'Infinite vs governed storage',
    deployment: 'Scheduled jobs',
    flow: 'Data → Lifecycle',
  },
  {
    id: 14,
    topic: 'Data Masking / Tokenization',
    definition: 'Protect sensitive data',
    implementation: 'Mask/tokenize PII fields',
    task: 'Apply transformation policies',
    service: 'Databricks / Security tools',
    deliverable: 'Masked dataset',
    validation: 'Mask validation',
    testing: 'Security tests',
    comparison: 'Plain vs protected data',
    deployment: 'Automated masking',
    flow: 'Raw → Protected',
  },
  {
    id: 15,
    topic: 'Data Access Workflow',
    definition: 'Control access requests',
    implementation: 'Implement approval workflows',
    task: 'Integrate request/approval system',
    service: 'IAM / ServiceNow',
    deliverable: 'Access workflow',
    validation: 'Approval validation',
    testing: 'Workflow tests',
    comparison: 'Direct vs controlled access',
    deployment: 'Automated workflow',
    flow: 'Request → Approval',
  },
  {
    id: 16,
    topic: 'Policy Enforcement',
    definition: 'Ensure rules are followed',
    implementation: 'Enforce policies programmatically',
    task: 'Monitor violations',
    service: 'Unity Catalog',
    deliverable: 'Policy engine',
    validation: 'Policy validation',
    testing: 'Violation tests',
    comparison: 'Manual vs enforced',
    deployment: 'Continuous enforcement',
    flow: 'Policy → Execution',
  },
  {
    id: 17,
    topic: 'Data Sharing Governance',
    definition: 'Secure data sharing',
    implementation: 'Define internal/external sharing rules',
    task: 'Use Delta Sharing',
    service: 'Databricks',
    deliverable: 'Shared datasets',
    validation: 'Access validation',
    testing: 'Sharing tests',
    comparison: 'Open vs governed sharing',
    deployment: 'Controlled sharing',
    flow: 'Data → Consumer',
  },
  {
    id: 18,
    topic: 'Multi-Environment Governance',
    definition: 'Separate Dev/QA/Prod access',
    implementation: 'Apply environment isolation',
    task: 'Manage cross-env controls',
    service: 'Databricks / IAM',
    deliverable: 'Environment policies',
    validation: 'Env validation',
    testing: 'Env tests',
    comparison: 'Mixed vs isolated env',
    deployment: 'Policy deployment',
    flow: 'Dev → Prod',
  },
  {
    id: 19,
    topic: 'Monitoring Governance Metrics',
    definition: 'Track governance health',
    implementation: 'Monitor access, quality, lineage metrics',
    task: 'Build dashboards',
    service: 'Datadog / Azure Monitor',
    deliverable: 'Governance dashboard',
    validation: 'KPI validation',
    testing: 'Alert tests',
    comparison: 'No visibility vs monitored',
    deployment: 'Continuous monitoring',
    flow: 'Metrics → Insight',
  },
  {
    id: 20,
    topic: 'Incident Governance',
    definition: 'Handle data breaches/issues',
    implementation: 'Define incident response plan',
    task: 'Implement escalation process',
    service: 'SIEM / SOC tools',
    deliverable: 'Incident report',
    validation: 'Incident validation',
    testing: 'Simulation tests',
    comparison: 'No process vs structured',
    deployment: 'Incident workflow',
    flow: 'Issue → Resolution',
  },
  {
    id: 21,
    topic: 'Data Stewardship',
    definition: 'Maintain data quality and usage',
    implementation: 'Assign stewards for datasets',
    task: 'Manage stewardship activities',
    service: 'Governance tools',
    deliverable: 'Steward registry',
    validation: 'Steward validation',
    testing: 'Review tests',
    comparison: 'No stewardship vs managed',
    deployment: 'Continuous governance',
    flow: 'Data → Steward',
  },
  {
    id: 22,
    topic: 'Business Glossary',
    definition: 'Define business terms',
    implementation: 'Standardize KPI and metric definitions',
    task: 'Maintain glossary',
    service: 'Collibra / UC',
    deliverable: 'Business glossary',
    validation: 'Definition validation',
    testing: 'Glossary tests',
    comparison: 'Undefined vs standardized',
    deployment: 'Continuous update',
    flow: 'Business → Data',
  },
  {
    id: 23,
    topic: 'Data Contract',
    definition: 'Define producer-consumer agreement',
    implementation: 'Set schema, SLA, quality expectations',
    task: 'Implement contracts',
    service: 'Databricks / API',
    deliverable: 'Data contract',
    validation: 'Contract validation',
    testing: 'Contract tests',
    comparison: 'No contract vs enforced',
    deployment: 'Integrated pipeline',
    flow: 'Source ↔ Consumer',
  },
  {
    id: 24,
    topic: 'Change Management',
    definition: 'Control schema and logic changes',
    implementation: 'Use versioning and approvals',
    task: 'Track changes',
    service: 'Git / UC',
    deliverable: 'Change log',
    validation: 'Change validation',
    testing: 'Regression tests',
    comparison: 'Uncontrolled vs governed',
    deployment: 'CI/CD deployment',
    flow: 'Change → Deployment',
  },
  {
    id: 25,
    topic: 'Data Risk Management',
    definition: 'Identify data risks',
    implementation: 'Assess privacy, security, compliance risks',
    task: 'Implement mitigation controls',
    service: 'Governance tools',
    deliverable: 'Risk assessment report',
    validation: 'Risk validation',
    testing: 'Risk tests',
    comparison: 'Unknown vs managed risk',
    deployment: 'Continuous monitoring',
    flow: 'Risk → Mitigation',
  },
  {
    id: 26,
    topic: 'Encryption',
    definition: 'Secure data at rest and transit',
    implementation: 'Enable encryption policies',
    task: 'Configure keys',
    service: 'Cloud KMS',
    deliverable: 'Encrypted data',
    validation: 'Encryption validation',
    testing: 'Security tests',
    comparison: 'Plain vs encrypted',
    deployment: 'Auto encryption',
    flow: 'Data → Secure',
  },
  {
    id: 27,
    topic: 'Secrets Management',
    definition: 'Secure credentials',
    implementation: 'Store secrets securely',
    task: 'Use vault systems',
    service: 'Azure Key Vault / AWS Secrets',
    deliverable: 'Secret store',
    validation: 'Access validation',
    testing: 'Security tests',
    comparison: 'Hardcoded vs secure',
    deployment: 'Vault integration',
    flow: 'Secrets → Access',
  },
  {
    id: 28,
    topic: 'Governance Automation',
    definition: 'Reduce manual effort',
    implementation: 'Automate tagging, policies, lineage',
    task: 'Build governance pipelines',
    service: 'Databricks / APIs',
    deliverable: 'Automated governance',
    validation: 'Automation validation',
    testing: 'Automation tests',
    comparison: 'Manual vs automated',
    deployment: 'CI/CD integration',
    flow: 'Data → Auto-governed',
  },
  {
    id: 29,
    topic: 'Cross-Platform Governance',
    definition: 'Multi-cloud governance alignment',
    implementation: 'Integrate Azure/AWS/GCP policies',
    task: 'Standardize governance',
    service: 'Multi-cloud tools',
    deliverable: 'Unified governance model',
    validation: 'Cross-platform validation',
    testing: 'Integration tests',
    comparison: 'Isolated vs unified',
    deployment: 'Policy sync',
    flow: 'Multi-cloud → Governance',
  },
  {
    id: 30,
    topic: 'Governance Reporting',
    definition: 'Provide governance insights',
    implementation: 'Build reports for compliance, usage',
    task: 'Publish dashboards',
    service: 'BI tools',
    deliverable: 'Governance reports',
    validation: 'Report validation',
    testing: 'UAT',
    comparison: 'No reporting vs insights',
    deployment: 'Scheduled refresh',
    flow: 'Governance → Reporting',
  },
];

export default function GovernanceImplementation() {
  return (
    <ImplementationLibrary
      pageTitle="Data Governance — Enterprise Implementation"
      pageSubtitle="30 governance patterns covering policy, RBAC, RLS/CLS, lineage, classification, compliance, stewardship, and automation."
      statsLabel="Governance Topics"
      rows={ROWS}
      csvName="governance-implementation.csv"
      accent="#10b981"
    />
  );
}
