import React from 'react';
import ChallengeLibrary from '../../components/architect/ChallengeLibrary';

const CHALLENGES = [
  // ── Setup & Environment (1-10) ──────────────────────────────────────
  {
    id: 1,
    title: 'Wrong Region Selected',
    description: 'Workspace in far region from data sources',
    scenario: 'Databricks in us-east but source DBs in eu-central',
    impact: 'High egress cost, latency, compliance violation',
    rootCause: 'Region chosen without data locality analysis',
    solution: 'Region assessment before workspace creation, data residency review',
    tools: 'Cloud region selection, data sovereignty policies',
  },
  {
    id: 2,
    title: 'VPC / VNet Peering Missed',
    description: 'Databricks cannot reach source databases',
    scenario: 'Source DB in corporate VPC; no peering established',
    impact: 'All ingestion blocked, project delayed weeks',
    rootCause: 'Network architecture not planned upfront',
    solution: 'Network architecture review before deploy, Private Link, VNet peering',
    tools: 'Private Link, VNet injection, Transit Gateway',
  },
  {
    id: 3,
    title: 'Private Endpoint Config Missed',
    description: 'Traffic routing via public internet',
    scenario: 'Enterprise security finds public traffic during audit',
    impact: 'Compliance finding, emergency rework',
    rootCause: 'Default deploy uses public endpoints',
    solution: 'Private endpoint required in deployment checklist',
    tools: 'Azure Private Link, AWS PrivateLink, no-public-IP clusters',
  },
  {
    id: 4,
    title: 'Storage Firewall Blocking DBX',
    description: 'Databricks cannot read ADLS/S3',
    scenario: 'Storage account firewall locked to corporate IPs only',
    impact: 'All jobs failing with 403',
    rootCause: 'Storage firewall not allowing Databricks subnet/identity',
    solution: 'Allowlist Databricks subnets, service endpoint, managed identity',
    tools: 'Storage firewall rules, service endpoints, UC external locations',
  },
  {
    id: 5,
    title: 'Service Principal Not Granted',
    description: 'Databricks SP missing role on storage',
    scenario: 'DevOps created SP but skipped Storage Blob Data Contributor',
    impact: 'Pipeline failing post-deploy, debugging day lost',
    rootCause: 'Missing IAM role assignment, manual setup',
    solution: 'Terraform-managed IAM, deployment checklist, UC credentials',
    tools: 'Terraform IAM, UC storage credentials',
  },
  {
    id: 6,
    title: 'Wrong Pricing Tier',
    description: 'Standard tier chosen; UC not available',
    scenario: 'Cost savings by picking Standard; UC governance blocked',
    impact: 'Cannot use Unity Catalog, migration needed',
    rootCause: 'Pricing tier decision not aligned to feature needs',
    solution: 'Premium tier for UC, map features to tier, TCO analysis',
    tools: 'Databricks pricing tiers, feature matrix',
  },
  {
    id: 7,
    title: 'Admin Role Sprawl',
    description: 'Everyone is workspace admin',
    scenario: '15 workspace admins, no change control',
    impact: 'Audit finding, accidental misconfig, security risk',
    rootCause: 'Easy path: granting admin to unblock work',
    solution: 'Least privilege, delegated admin via groups, audit admin actions',
    tools: 'UC account-level admin, workspace admin separation',
  },
  {
    id: 8,
    title: 'No Multi-Workspace Strategy',
    description: 'One workspace for dev/qa/prod',
    scenario: 'Dev workloads starving prod of resources',
    impact: 'Production instability, no isolation',
    rootCause: 'Cost-driven single-workspace decision',
    solution: 'Separate workspaces per env, shared UC metastore',
    tools: 'Multi-workspace with shared UC',
  },
  {
    id: 9,
    title: 'Dev/QA/Prod Collapsed',
    description: 'Testing in production workspace',
    scenario: 'Dev code tested in prod "to save workspace cost"',
    impact: 'Prod outages from dev experiments',
    rootCause: 'Budget constraint at setup time',
    solution: 'Mandate env separation, DAB (Databricks Asset Bundles) for promotion',
    tools: 'Databricks Asset Bundles, workspace-per-env',
  },
  {
    id: 10,
    title: 'Cluster Policies Not Enforced',
    description: 'Users create arbitrary-size clusters',
    scenario: 'User spun up 32-node GPU cluster for small task',
    impact: 'Cost overruns, resource hoarding',
    rootCause: 'No cluster policies; only UI restrictions',
    solution: 'Mandatory cluster policies, policy families, deny-by-default',
    tools: 'Cluster policies JSON, policy families',
  },

  // ── Integration (11-20) ─────────────────────────────────────────────
  {
    id: 11,
    title: 'Source Data Contract Undefined',
    description: 'No formal agreement with source team',
    scenario: 'Source team renamed columns without notice; pipeline broke',
    impact: 'Frequent pipeline failures, firefighting culture',
    rootCause: 'No contract or communication channel with source',
    solution: 'Data contracts with schema/SLA, producer-consumer review',
    tools: 'Data contract templates, schema registry, Kafka schema contracts',
  },
  {
    id: 12,
    title: 'JDBC Driver Version Mismatch',
    description: 'Dev works, prod fails on JDBC read',
    scenario: 'Dev cluster auto-updated driver; prod pinned to old version',
    impact: 'Release blocked, version drift',
    rootCause: 'Unpinned dependencies, runtime version drift',
    solution: 'Pin DBR version, test in staging matching prod',
    tools: 'DBR version pinning, cluster libraries',
  },
  {
    id: 13,
    title: 'Schema Registry URL Hardcoded',
    description: 'Kafka URL in code; cannot promote between envs',
    scenario: 'Notebook hardcodes dev Kafka; fails in prod',
    impact: 'Manual find-replace per promotion, errors',
    rootCause: 'No env config, hardcoded URLs',
    solution: 'Env vars via secret scope, parameterized notebook',
    tools: 'Databricks Secrets, env-specific config',
  },
  {
    id: 14,
    title: 'Partner Access Model Unclear',
    description: 'External partner asking for data; no sharing model',
    scenario: 'CSV email workflow set up as "interim" — still used 2yr later',
    impact: 'No audit, compliance risk, stale data',
    rootCause: 'No formal partner sharing architecture',
    solution: 'Delta Sharing for all partners, signed agreement',
    tools: 'Delta Sharing, recipient management',
  },
  {
    id: 15,
    title: 'BI Connection Credentials Leaked',
    description: 'Power BI connection string in report metadata',
    scenario: 'Report downloaded shows PAT in connection',
    impact: 'PAT leaked, security incident',
    rootCause: 'Personal Access Tokens in BI config',
    solution: 'OAuth service principal auth, no PATs in reports',
    tools: 'OAuth, Service Principal BI connectivity',
  },
  {
    id: 16,
    title: 'API Rate Limits Not Negotiated',
    description: 'Source API throttling ingestion',
    scenario: 'Salesforce API limit of 100k/day; ingestion needs 500k',
    impact: 'Incomplete data, ingestion takes 5 days',
    rootCause: 'Rate limits not discussed with source team',
    solution: 'Negotiate bulk API quota, Bulk API 2.0, incremental pulls',
    tools: 'API rate limit negotiation, Salesforce Bulk API',
  },
  {
    id: 17,
    title: 'Legacy ETL Team Not Engaged',
    description: 'Existing ETL team blocking migration',
    scenario: 'Legacy SSIS team not consulted; duplicate pipelines built',
    impact: 'Political conflict, duplicate cost, adoption failure',
    rootCause: 'Migration designed without legacy owner input',
    solution: 'Include legacy team from day 1, co-design migration',
    tools: 'Stakeholder engagement, migration runbook',
  },
  {
    id: 18,
    title: 'dbt Version Conflict',
    description: 'dbt-databricks adapter incompatible with dbt Core version',
    scenario: 'dbt upgrade broke all existing models',
    impact: 'CI/CD broken, release blocked',
    rootCause: 'Unpinned dbt, unpinned adapter',
    solution: 'Pin dbt + adapter + DBR, test matrix',
    tools: 'dbt requirements pinning',
  },
  {
    id: 19,
    title: 'dbt Core vs dbt Cloud Mixed',
    description: 'Some models in dbt Core, some in Cloud',
    scenario: 'Two teams picked different dbt flavors',
    impact: 'Duplicate infrastructure, sync complexity',
    rootCause: 'No org-level dbt strategy',
    solution: 'Pick one, migrate, enforce standard',
    tools: 'dbt governance policy',
  },
  {
    id: 20,
    title: 'Spark Version Pinned Wrong',
    description: 'DBR version below feature requirement',
    scenario: 'Code using Delta feature not in pinned DBR',
    impact: 'Feature unavailable, workaround complexity',
    rootCause: 'DBR pinning without feature review',
    solution: 'DBR version selection aligned to feature roadmap',
    tools: 'DBR release notes, Delta feature matrix',
  },

  // ── Code / Pipelines (21-30) ────────────────────────────────────────
  {
    id: 21,
    title: 'No Coding Standards',
    description: 'Each team writes PySpark differently',
    scenario: 'Review comments endless; code reuse impossible',
    impact: 'Slow reviews, bugs, low reuse',
    rootCause: 'No style guide, no linting in CI',
    solution: 'PEP8 + PySpark guide, black + ruff in CI, pull request template',
    tools: 'black, ruff, pre-commit hooks',
  },
  {
    id: 22,
    title: 'Notebooks Not in Git',
    description: 'Notebooks saved only in workspace',
    scenario: 'User deleted important notebook; no recovery',
    impact: 'Lost work, no version history, no peer review',
    rootCause: 'Databricks Repos not mandated',
    solution: 'Mandatory Git via Databricks Repos, branch protection',
    tools: 'Databricks Repos, Git provider integration',
  },
  {
    id: 23,
    title: 'No CI/CD for DBX Assets',
    description: 'Manual notebook upload per env',
    scenario: 'Engineer drags notebook from dev to prod workspace',
    impact: 'Errors, no audit, slow release',
    rootCause: 'No CI/CD maturity, setup skipped',
    solution: 'Databricks Asset Bundles + GitHub Actions / Azure DevOps',
    tools: 'Databricks Asset Bundles (DAB), CI/CD pipelines',
  },
  {
    id: 24,
    title: 'Secrets in Notebooks',
    description: 'Hardcoded passwords despite Key Vault',
    scenario: 'Secret scope exists but user pastes password "temporarily"',
    impact: 'Credentials leaked via exported notebook',
    rootCause: 'No scanning, easier to paste',
    solution: 'Secret scanning in CI, training, dbutils.secrets.get()',
    tools: 'detect-secrets, Databricks Secrets API',
  },
  {
    id: 25,
    title: 'Hardcoded Paths',
    description: 'dbfs:/path/dev/... in production code',
    scenario: 'Same path works in dev but reads stale data in prod',
    impact: 'Wrong data read, investigation time',
    rootCause: 'No path parameterization',
    solution: 'Widget parameters, env-specific config, UC abstracts path',
    tools: 'dbutils.widgets, UC table references',
  },
  {
    id: 26,
    title: 'Shared Notebooks No ACL',
    description: 'Everyone has write access to critical notebook',
    scenario: 'Junior engineer accidentally overwrote prod logic',
    impact: 'Production outage, rollback needed',
    rootCause: 'Default workspace-wide access, no ACL',
    solution: 'ACLs per folder, Repos for production code',
    tools: 'Workspace ACLs, Repos branch permissions',
  },
  {
    id: 27,
    title: 'No Unit Test Framework',
    description: 'PySpark logic untested until prod',
    scenario: 'SCD logic bug surfaces in production',
    impact: 'Silent data corruption, costly rework',
    rootCause: 'No test harness, no test culture',
    solution: 'pytest + chispa for Spark, test in CI',
    tools: 'pytest, chispa, Databricks Connect for local testing',
  },
  {
    id: 28,
    title: 'Manual Table Creation',
    description: 'Tables created via UI, not IaC',
    scenario: 'Dev table structure differs from prod; hard to track',
    impact: 'Environment drift, reproduction failures',
    rootCause: 'UI convenience, no IaC discipline',
    solution: 'Terraform + DAB for all tables, SQL migrations',
    tools: 'Terraform Databricks provider, DAB',
  },
  {
    id: 29,
    title: 'Pipeline Logic in BI Tool',
    description: 'Business logic in Power BI measures',
    scenario: 'KPI calculated only in BI, duplicated across reports',
    impact: 'Inconsistent KPI, cannot reuse, BI tool lock-in',
    rootCause: 'Logic pushed to BI for speed',
    solution: 'Logic in Gold tables / semantic layer; BI just visualizes',
    tools: 'dbt metrics, Databricks metric views',
  },
  {
    id: 30,
    title: 'Stored Procedures Badly Migrated',
    description: 'SQL Server SPs translated 1:1 to Spark',
    scenario: 'Cursor-based SP migrated as Spark UDF; very slow',
    impact: 'Jobs 10x slower, abandoned project',
    rootCause: 'Direct translation without Spark-native rewrite',
    solution: 'Rewrite using Spark/SQL patterns, avoid row-by-row',
    tools: 'Spark SQL, set-based operations',
  },

  // ── Governance (31-40) ──────────────────────────────────────────────
  {
    id: 31,
    title: 'UC Rollout Delayed',
    description: 'Hive Metastore still primary after go-live',
    scenario: 'UC migration deprioritized; 2000 HMS tables',
    impact: 'Missing governance features, tech debt',
    rootCause: 'UC not in original scope',
    solution: 'UC migration phased plan, automated migration tools',
    tools: 'UC migration assistant, SYNC command',
  },
  {
    id: 32,
    title: 'Table-Only Access Control',
    description: 'No column/row-level security',
    scenario: 'Full table shared despite only 3 columns needed',
    impact: 'Over-sharing, audit finding',
    rootCause: 'RLS/CLS not implemented in initial rollout',
    solution: 'UC row filters + column masks, view-based RLS',
    tools: 'UC ROW FILTER, COLUMN MASK, dynamic views',
  },
  {
    id: 33,
    title: 'No Data Classification',
    description: 'PII not tagged',
    scenario: 'Cannot identify which tables have PII for GDPR',
    impact: 'Compliance risk, manual audits',
    rootCause: 'Classification deferred to later phase',
    solution: 'Automated PII scan + UC tags as day-0 requirement',
    tools: 'UC tags, PII scanners (Privacera, Immuta)',
  },
  {
    id: 34,
    title: 'Business Glossary Empty',
    description: 'UC deployed but no business definitions',
    scenario: 'Analysts cannot discover relevant data',
    impact: 'Low adoption, duplicate tables',
    rootCause: 'Technical-only deployment; no data stewards',
    solution: 'Steward program, UC comments + tags, Collibra integration',
    tools: 'UC COMMENT, tags, Collibra sync',
  },
  {
    id: 35,
    title: 'Lineage Not Enabled',
    description: 'Cannot trace which report uses which table',
    scenario: 'Incident — unclear impact radius',
    impact: 'Slow debugging, impact analysis manual',
    rootCause: 'UC lineage not enabled initially',
    solution: 'Enable system.access.table_lineage from day 1',
    tools: 'UC system tables, OpenLineage',
  },
  {
    id: 36,
    title: 'Audit Log Retention Too Short',
    description: '30 days retention; compliance needs 1 year',
    scenario: 'Audit requesting access log from 6 months ago',
    impact: 'Cannot answer audit, fine risk',
    rootCause: 'Default retention accepted',
    solution: 'Extend retention, export audit logs to immutable storage',
    tools: 'Diagnostic settings, UC system.access schema',
  },
  {
    id: 37,
    title: 'External Sharing Uncontrolled',
    description: 'CSVs emailed to partners regularly',
    scenario: 'Finance team emails daily reports to vendor',
    impact: 'No audit, data leak risk',
    rootCause: 'No sharing policy, convenience',
    solution: 'Delta Sharing only, ban CSV exports, audit email data',
    tools: 'Delta Sharing, DLP tools',
  },
  {
    id: 38,
    title: 'Compliance Team Late',
    description: 'Compliance involved just before go-live',
    scenario: 'Audit requirements surface in UAT; 3-month delay',
    impact: 'Go-live slipped, rework cost',
    rootCause: 'Compliance not in steering committee',
    solution: 'Compliance + Legal in design phase, compliance-as-code',
    tools: 'Steering committee governance, compliance framework',
  },
  {
    id: 39,
    title: 'Service Account Sprawl',
    description: '100+ service principals, unclear ownership',
    scenario: 'Cannot determine which SP is safe to delete',
    impact: 'Security risk, cost, cleanup paralysis',
    rootCause: 'Ad-hoc SP creation, no naming/tagging',
    solution: 'SP naming convention, tagging, quarterly review',
    tools: 'Azure AD / IAM governance, tagging',
  },
  {
    id: 40,
    title: 'Stale Group Membership',
    description: 'Departed employees still in groups',
    scenario: 'Ex-employee still has access 6 months later',
    impact: 'Security risk, audit finding',
    rootCause: 'No IdP sync, no offboarding workflow',
    solution: 'SCIM integration, automated deprovisioning, quarterly reviews',
    tools: 'SCIM, Azure AD sync, Okta',
  },

  // ── Ops / Production (41-50) ────────────────────────────────────────
  {
    id: 41,
    title: 'No Monitoring Plan',
    description: 'Go-live without dashboards or alerts',
    scenario: 'Production issues found by users, not ops',
    impact: 'Long MTTR, trust erosion',
    rootCause: 'Monitoring deferred to "phase 2"',
    solution: 'Monitoring as day-0: SLOs, dashboards, alerts, runbooks',
    tools: 'Datadog, Databricks system tables, PagerDuty',
  },
  {
    id: 42,
    title: 'No FinOps from Day 1',
    description: 'Cost tracking added after bill shock',
    scenario: 'First-month bill 3x expected; no visibility',
    impact: 'Credibility loss, emergency cuts',
    rootCause: 'FinOps seen as optional',
    solution: 'Tags + chargeback dashboard from workspace creation',
    tools: 'system.billing.usage, cost dashboards, cluster policies',
  },
  {
    id: 43,
    title: 'No Runbooks',
    description: 'On-call has no docs for common issues',
    scenario: '3am page — on-call has no idea how to fix',
    impact: 'Long MTTR, escalation to dev team',
    rootCause: 'Runbooks deferred; production knowledge tribal',
    solution: 'Runbook per pipeline + per alert; test during game days',
    tools: 'Confluence/Notion runbooks, linked from alerts',
  },
  {
    id: 44,
    title: 'No On-Call Rotation',
    description: 'Ops goes to random Slack channel',
    scenario: 'Critical issue at night, no response for hours',
    impact: 'Long outages, customer impact',
    rootCause: 'No on-call formalized',
    solution: 'PagerDuty/Opsgenie rotation, escalation policy, comp pay',
    tools: 'PagerDuty, Opsgenie, escalation policies',
  },
  {
    id: 45,
    title: 'Alerts to Shared Inbox',
    description: 'Alerts in team@company.com inbox, ignored',
    scenario: '500 alerts/day in inbox; critical ones lost',
    impact: 'Alert fatigue, missed incidents',
    rootCause: 'Email-only alerting, no triage system',
    solution: 'Route critical alerts to PagerDuty, email for low-severity',
    tools: 'Alertmanager, PagerDuty, severity-based routing',
  },
  {
    id: 46,
    title: 'DR Untested',
    description: 'Disaster recovery plan on paper but never tested',
    scenario: 'Region outage — DR plan fails; team improvises',
    impact: 'Extended outage, data loss',
    rootCause: 'DR tests not scheduled',
    solution: 'Quarterly DR tests, game days, automated failover',
    tools: 'Multi-region replication, chaos engineering',
  },
  {
    id: 47,
    title: 'No Delta Backup Strategy',
    description: 'Relying only on Delta time travel',
    scenario: 'Accidental DROP TABLE; time travel retention 7 days only',
    impact: 'Table loss, recovery complexity',
    rootCause: 'Assumed Delta time travel is backup',
    solution: 'Cross-region DEEP CLONE backups, long retention, separate storage',
    tools: 'DEEP CLONE, storage replication',
  },
  {
    id: 48,
    title: 'Environment Drift',
    description: 'Dev and prod configurations diverged',
    scenario: "Prod has special config that dev doesn't; dev tests misleading",
    impact: 'Prod bugs not caught in dev',
    rootCause: 'Manual config changes, no IaC enforcement',
    solution: 'Full IaC with Terraform, config diff alerts',
    tools: 'Terraform, drift detection, pull-based GitOps',
  },
  {
    id: 49,
    title: 'No Load Testing',
    description: 'Go-live without scale testing',
    scenario: 'First prod run fails — cluster too small for real volume',
    impact: 'Emergency scale-up, missed SLA',
    rootCause: 'Dev data volume << prod volume; no scale test',
    solution: 'Production-like volume tests in staging, synthetic data',
    tools: 'Synthetic data, staging workspace, scale testing',
  },
  {
    id: 50,
    title: 'No Rollback Plan',
    description: 'Bad release in prod with no rollback',
    scenario: 'Bug released; team firefights without rollback strategy',
    impact: 'Extended incident, data corruption risk',
    rootCause: 'Forward-only deploy assumption',
    solution: 'Blue/green deploy, feature flags, table versioning, documented rollback',
    tools: 'Databricks Asset Bundles, Delta time travel, feature flags',
  },
];

export default function ImplementationIssues() {
  return (
    <ChallengeLibrary
      pageTitle="Implementation Issues — 50 Setup & Rollout Pitfalls"
      pageSubtitle="Setup, integration, code, governance, and ops issues encountered during Databricks/Lakehouse implementation — with architect-level root cause and resolution."
      statsLabel="Implementation Issues"
      totalCount={50}
      challenges={CHALLENGES}
      domain="strategy"
      csvName="implementation-issues.csv"
    />
  );
}
