import React from 'react';
import ImplementationLibrary from '../../components/architect/ImplementationLibrary';

const ROWS = [
  {
    id: 1,
    topic: 'Source Identification',
    definition: 'Identify all data sources',
    implementation: 'List APIs, DBs, files, streams',
    task: 'Analyze systems',
    service: 'Azure / AWS',
    deliverable: 'Source catalog',
    validation: 'Cross-check with business',
    testing: 'Source connectivity test',
    comparison: 'Batch vs Streaming',
    deployment: 'Config-driven deployment',
    flow: 'Source → Ingestion',
  },
  {
    id: 2,
    topic: 'Data Ingestion Strategy',
    definition: 'Define ingestion approach',
    implementation: 'Batch / Streaming / CDC selection',
    task: 'Choose ingestion pattern',
    service: 'Databricks',
    deliverable: 'Architecture doc',
    validation: 'Business approval',
    testing: 'Load testing',
    comparison: 'Batch vs Streaming',
    deployment: 'Parameterized jobs',
    flow: 'Source → Bronze',
  },
  {
    id: 3,
    topic: 'File Ingestion',
    definition: 'Load files into lake',
    implementation: 'Use Auto Loader',
    task: 'Configure file ingestion',
    service: 'ADLS / S3',
    deliverable: 'Bronze tables',
    validation: 'File count match',
    testing: 'File format test',
    comparison: 'CSV vs Parquet',
    deployment: 'Scheduled job',
    flow: 'File → Bronze',
  },
  {
    id: 4,
    topic: 'API Ingestion',
    definition: 'Pull data from APIs',
    implementation: 'REST API integration',
    task: 'Build API connector',
    service: 'Python / REST',
    deliverable: 'API ingestion pipeline',
    validation: 'Response validation',
    testing: 'API response test',
    comparison: 'API vs CDC',
    deployment: 'CI/CD deployment',
    flow: 'API → Bronze',
  },
  {
    id: 5,
    topic: 'Streaming Ingestion',
    definition: 'Real-time ingestion',
    implementation: 'Kafka/Event Hub integration',
    task: 'Configure streaming job',
    service: 'Kafka / Event Hub',
    deliverable: 'Streaming pipeline',
    validation: 'Offset validation',
    testing: 'Latency test',
    comparison: 'Batch vs Streaming',
    deployment: 'Continuous job',
    flow: 'Stream → Bronze',
  },
  {
    id: 6,
    topic: 'Schema Management',
    definition: 'Handle schema evolution',
    implementation: 'Infer + enforce schema',
    task: 'Define schema rules',
    service: 'Delta Lake',
    deliverable: 'Schema registry',
    validation: 'Schema validation',
    testing: 'Schema drift test',
    comparison: 'Static vs dynamic schema',
    deployment: 'Version control',
    flow: 'Data → Schema',
  },
  {
    id: 7,
    topic: 'Data Partitioning',
    definition: 'Optimize storage layout',
    implementation: 'Partition by date/key',
    task: 'Define partition logic',
    service: 'Delta Lake',
    deliverable: 'Partitioned tables',
    validation: 'Partition check',
    testing: 'Query test',
    comparison: 'Partition vs no partition',
    deployment: 'Auto partition deploy',
    flow: 'Data → Partition',
  },
  {
    id: 8,
    topic: 'Metadata Capture',
    definition: 'Track ingestion metadata',
    implementation: 'Store file name, timestamp',
    task: 'Add audit columns',
    service: 'Databricks',
    deliverable: 'Metadata table',
    validation: 'Metadata validation',
    testing: 'Audit test',
    comparison: 'With vs without metadata',
    deployment: 'Auto capture',
    flow: 'Data → Metadata',
  },
  {
    id: 9,
    topic: 'Data Quality Check',
    definition: 'Validate incoming data',
    implementation: 'Apply validation rules',
    task: 'Create DQ checks',
    service: 'Great Expectations / dbt',
    deliverable: 'Quality report',
    validation: 'Rule validation',
    testing: 'DQ test',
    comparison: 'With vs without validation',
    deployment: 'Integrated pipeline',
    flow: 'Data → Quality',
  },
  {
    id: 10,
    topic: 'Error Handling',
    definition: 'Handle failures',
    implementation: 'Retry / quarantine',
    task: 'Build error framework',
    service: 'Databricks',
    deliverable: 'Error logs',
    validation: 'Error detection',
    testing: 'Failure simulation',
    comparison: 'Retry vs fail',
    deployment: 'Auto retry deploy',
    flow: 'Data → Error',
  },
  {
    id: 11,
    topic: 'Incremental Load',
    definition: 'Load only new data',
    implementation: 'Use watermark/CDC',
    task: 'Implement incremental logic',
    service: 'Delta Lake',
    deliverable: 'Incremental pipeline',
    validation: 'Data comparison',
    testing: 'Delta test',
    comparison: 'Full vs incremental',
    deployment: 'Scheduled job',
    flow: 'Source → Delta',
  },
  {
    id: 12,
    topic: 'Data Storage (Bronze)',
    definition: 'Store raw data',
    implementation: 'Write to Delta Bronze',
    task: 'Configure storage',
    service: 'Delta Lake',
    deliverable: 'Bronze tables',
    validation: 'Row count validation',
    testing: 'Storage test',
    comparison: 'Raw vs curated',
    deployment: 'Automated pipeline',
    flow: 'Data → Bronze',
  },
  {
    id: 13,
    topic: 'Security (Ingestion)',
    definition: 'Secure data access',
    implementation: 'RBAC / encryption',
    task: 'Configure IAM',
    service: 'Unity Catalog',
    deliverable: 'Access control',
    validation: 'Permission test',
    testing: 'Security test',
    comparison: 'Open vs secure',
    deployment: 'Policy deploy',
    flow: 'Access → Data',
  },
  {
    id: 14,
    topic: 'Orchestration',
    definition: 'Manage pipeline flow',
    implementation: 'Use workflows',
    task: 'Define DAGs',
    service: 'Airflow / Workflows',
    deliverable: 'Pipeline schedule',
    validation: 'Dependency validation',
    testing: 'Workflow test',
    comparison: 'Manual vs automated',
    deployment: 'CI/CD deploy',
    flow: 'Step → Step',
  },
  {
    id: 15,
    topic: 'Monitoring',
    definition: 'Track ingestion health',
    implementation: 'Metrics + alerts',
    task: 'Configure monitoring',
    service: 'Datadog / Azure Monitor',
    deliverable: 'Dashboard',
    validation: 'Alert validation',
    testing: 'Alert test',
    comparison: 'With vs without monitoring',
    deployment: 'Integrated monitoring',
    flow: 'Pipeline → Metrics',
  },
  {
    id: 16,
    topic: 'Logging',
    definition: 'Capture execution logs',
    implementation: 'Store logs centrally',
    task: 'Configure logging',
    service: 'Log Analytics',
    deliverable: 'Log store',
    validation: 'Log validation',
    testing: 'Debug test',
    comparison: 'Basic vs structured logs',
    deployment: 'Auto logging',
    flow: 'Job → Logs',
  },
  {
    id: 17,
    topic: 'Performance Optimization',
    definition: 'Improve ingestion speed',
    implementation: 'Optimize file size, parallelism',
    task: 'Tune Spark jobs',
    service: 'Databricks',
    deliverable: 'Optimized jobs',
    validation: 'Performance metrics',
    testing: 'Load test',
    comparison: 'Tuned vs untuned',
    deployment: 'Config deploy',
    flow: 'Data → Optimized',
  },
  {
    id: 18,
    topic: 'Data Lineage',
    definition: 'Track data flow',
    implementation: 'Enable lineage tracking',
    task: 'Integrate catalog',
    service: 'Unity Catalog',
    deliverable: 'Lineage graph',
    validation: 'Lineage validation',
    testing: 'Audit test',
    comparison: 'With vs without lineage',
    deployment: 'Auto lineage',
    flow: 'Source → BI',
  },
  {
    id: 19,
    topic: 'CI/CD Integration',
    definition: 'Automate deployment',
    implementation: 'Git + pipelines',
    task: 'Build CI/CD',
    service: 'GitHub Actions',
    deliverable: 'Deployment pipeline',
    validation: 'Build validation',
    testing: 'Deploy test',
    comparison: 'Manual vs CI/CD',
    deployment: 'Automated deploy',
    flow: 'Code → Prod',
  },
  {
    id: 20,
    topic: 'SLA Management',
    definition: 'Ensure timely ingestion',
    implementation: 'Define SLA rules',
    task: 'Configure alerts',
    service: 'Monitoring tools',
    deliverable: 'SLA report',
    validation: 'SLA validation',
    testing: 'Delay test',
    comparison: 'With vs without SLA',
    deployment: 'Alert system',
    flow: 'Time → Delivery',
  },
];

export default function IngestionImplementation() {
  return (
    <ImplementationLibrary
      pageTitle="Data Ingestion — Enterprise Implementation"
      pageSubtitle="20 end-to-end implementation patterns covering source identification, strategy, quality, orchestration, and SLA."
      statsLabel="Implementation Topics"
      rows={ROWS}
      csvName="ingestion-implementation.csv"
      accent="#3b82f6"
    />
  );
}
