import React from 'react';
import ChallengeLibrary from '../../components/architect/ChallengeLibrary';

const CHALLENGES = [
  {
    id: 1,
    title: 'Data Volume',
    description: 'Large data ingestion slows pipelines',
    scenario: '1TB/day transaction ingestion',
    impact: 'Delays, SLA breach',
    rootCause: 'No partitioning, poor scaling',
    solution: 'Partition + parallel ingestion',
    tools: 'Auto Loader, Spark',
  },
  {
    id: 2,
    title: 'Data Velocity',
    description: 'Real-time ingestion not handled',
    scenario: 'Kafka streaming spikes',
    impact: 'Data lag',
    rootCause: 'No streaming design',
    solution: 'Structured streaming',
    tools: 'Kafka, Spark Streaming',
  },
  {
    id: 3,
    title: 'Data Variety',
    description: 'Multiple formats (JSON, CSV, XML)',
    scenario: 'ERP + CRM + logs',
    impact: 'Parsing errors',
    rootCause: 'No schema standard',
    solution: 'Schema normalization',
    tools: 'Spark, schema registry',
  },
  {
    id: 4,
    title: 'Schema Evolution',
    description: 'Schema changes break pipeline',
    scenario: 'New column added in source',
    impact: 'Job failure',
    rootCause: 'Rigid schema',
    solution: 'Enable schema evolution',
    tools: 'Auto Loader',
  },
  {
    id: 5,
    title: 'Data Quality',
    description: 'Bad/dirty data ingestion',
    scenario: 'Missing fields, nulls',
    impact: 'Wrong analytics',
    rootCause: 'No validation layer',
    solution: 'Data validation rules',
    tools: 'Great Expectations',
  },
  {
    id: 6,
    title: 'Duplicate Data',
    description: 'Same data ingested multiple times',
    scenario: 'CDC + batch overlap',
    impact: 'Incorrect reporting',
    rootCause: 'No dedup logic',
    solution: 'Deduplication logic',
    tools: 'Delta Lake',
  },
  {
    id: 7,
    title: 'Late Arriving Data',
    description: 'Data arrives after processing window',
    scenario: 'Delayed transactions',
    impact: 'Incomplete dataset',
    rootCause: 'No watermarking',
    solution: 'Handle late data',
    tools: 'Structured Streaming',
  },
  {
    id: 8,
    title: 'Data Loss',
    description: 'Missing records during ingestion',
    scenario: 'Network failure drops records',
    impact: 'Incomplete data',
    rootCause: 'No retry mechanism',
    solution: 'Retry + checkpointing',
    tools: 'Spark checkpoint',
  },
  {
    id: 9,
    title: 'Connectivity Issues',
    description: 'Source connection unstable',
    scenario: 'API timeout from CRM',
    impact: 'Pipeline failure',
    rootCause: 'Weak network handling',
    solution: 'Retry + backoff',
    tools: 'API connectors',
  },
  {
    id: 10,
    title: 'API Limits',
    description: 'Rate limits on APIs',
    scenario: 'Salesforce API throttling',
    impact: 'Partial ingestion',
    rootCause: 'No throttling control',
    solution: 'Rate limiting logic',
    tools: 'API gateway',
  },
  {
    id: 11,
    title: 'CDC Complexity',
    description: 'Change Data Capture inconsistent',
    scenario: 'DB updates not captured correctly',
    impact: 'Data mismatch',
    rootCause: 'Poor CDC design',
    solution: 'CDC framework',
    tools: 'Debezium, Delta',
  },
  {
    id: 12,
    title: 'File Explosion',
    description: 'Too many small files',
    scenario: 'Millions of small JSON files',
    impact: 'Performance issue',
    rootCause: 'No file compaction',
    solution: 'Optimize files',
    tools: 'Delta OPTIMIZE',
  },
  {
    id: 13,
    title: 'Security',
    description: 'Sensitive data exposure',
    scenario: 'PII in raw ingestion',
    impact: 'Compliance risk',
    rootCause: 'No masking',
    solution: 'Mask/tokenize data',
    tools: 'Unity Catalog',
  },
  {
    id: 14,
    title: 'Access Control',
    description: 'Unauthorized ingestion access',
    scenario: 'Anyone can ingest data',
    impact: 'Data corruption',
    rootCause: 'Weak IAM',
    solution: 'RBAC policies',
    tools: 'IAM, Unity Catalog',
  },
  {
    id: 15,
    title: 'Data Lineage Missing',
    description: 'No trace of data origin',
    scenario: 'Cannot track source',
    impact: 'Debug difficulty',
    rootCause: 'No lineage tracking',
    solution: 'Enable lineage',
    tools: 'Unity Catalog',
  },
  {
    id: 16,
    title: 'Metadata Management',
    description: 'No metadata captured',
    scenario: 'Tables undocumented',
    impact: 'Poor discoverability',
    rootCause: 'No catalog',
    solution: 'Metadata catalog',
    tools: 'Collibra, UC',
  },
  {
    id: 17,
    title: 'Format Inconsistency',
    description: 'Same field different formats',
    scenario: 'Date in multiple formats',
    impact: 'Transformation errors',
    rootCause: 'No standardization',
    solution: 'Format standard rules',
    tools: 'Spark',
  },
  {
    id: 18,
    title: 'Time Zone Issues',
    description: 'Different time zones in data',
    scenario: 'Global transactions',
    impact: 'Wrong aggregation',
    rootCause: 'No timezone normalization',
    solution: 'Standard UTC',
    tools: 'Spark functions',
  },
  {
    id: 19,
    title: 'Data Drift',
    description: 'Source data changes over time',
    scenario: 'New patterns in data',
    impact: 'Pipeline instability',
    rootCause: 'No monitoring',
    solution: 'Drift detection',
    tools: 'Monitoring tools',
  },
  {
    id: 20,
    title: 'Error Handling',
    description: 'No proper error capture',
    scenario: 'Pipeline crashes silently',
    impact: 'Data loss',
    rootCause: 'No logging',
    solution: 'Error handling framework',
    tools: 'Logging tools',
  },
  {
    id: 21,
    title: 'Retry Logic',
    description: 'No retry mechanism',
    scenario: 'Temporary failure stops job',
    impact: 'Pipeline failure',
    rootCause: 'Weak design',
    solution: 'Retry with backoff',
    tools: 'Workflow tools',
  },
  {
    id: 22,
    title: 'Dependency Handling',
    description: 'Source dependency not managed',
    scenario: 'Upstream job fails',
    impact: 'Downstream failure',
    rootCause: 'No orchestration',
    solution: 'Workflow orchestration',
    tools: 'Airflow, Workflows',
  },
  {
    id: 23,
    title: 'Batch vs Streaming Conflict',
    description: 'Mixed ingestion design unclear',
    scenario: 'Same data via batch + stream',
    impact: 'Duplication',
    rootCause: 'Poor architecture',
    solution: 'Clear ingestion strategy',
    tools: 'Lambda/Kappa',
  },
  {
    id: 24,
    title: 'Data Partitioning',
    description: 'Improper partitioning',
    scenario: 'Large unpartitioned tables',
    impact: 'Slow reads',
    rootCause: 'Poor design',
    solution: 'Partition strategy',
    tools: 'Delta Lake',
  },
  {
    id: 25,
    title: 'Storage Layout',
    description: 'Poor file organization',
    scenario: 'Data scattered randomly',
    impact: 'Hard querying',
    rootCause: 'No structure',
    solution: 'Standard folder structure',
    tools: 'Lakehouse design',
  },
  {
    id: 26,
    title: 'Monitoring',
    description: 'No ingestion monitoring',
    scenario: 'No visibility of failures',
    impact: 'Delayed detection',
    rootCause: 'No observability',
    solution: 'Monitoring dashboards',
    tools: 'Databricks UI',
  },
  {
    id: 27,
    title: 'Logging',
    description: 'No logs for ingestion',
    scenario: 'Cannot debug issues',
    impact: 'Delay in fix',
    rootCause: 'Missing logs',
    solution: 'Central logging',
    tools: 'ELK, Splunk',
  },
  {
    id: 28,
    title: 'Cost Control',
    description: 'High ingestion cost',
    scenario: 'Continuous ingestion jobs',
    impact: 'Budget issues',
    rootCause: 'Inefficient compute',
    solution: 'Optimize jobs',
    tools: 'FinOps tools',
  },
  {
    id: 29,
    title: 'Data Encryption',
    description: 'Data not encrypted',
    scenario: 'Raw data exposed',
    impact: 'Security risk',
    rootCause: 'No encryption',
    solution: 'Encrypt at rest/in transit',
    tools: 'Cloud encryption',
  },
  {
    id: 30,
    title: 'Multi-source Sync',
    description: 'Multiple sources not aligned',
    scenario: 'ERP vs CRM mismatch',
    impact: 'Data inconsistency',
    rootCause: 'No sync strategy',
    solution: 'Data reconciliation',
    tools: 'ETL pipelines',
  },
  {
    id: 31,
    title: 'Data Freshness',
    description: 'Delay in ingestion',
    scenario: 'Data not near real-time',
    impact: 'Poor decisions',
    rootCause: 'Batch-only design',
    solution: 'Streaming ingestion',
    tools: 'Kafka',
  },
  {
    id: 32,
    title: 'Governance',
    description: 'No ingestion policy',
    scenario: 'Different teams ingest differently',
    impact: 'Chaos',
    rootCause: 'No standards',
    solution: 'Governance framework',
    tools: 'UC, Collibra',
  },
  {
    id: 33,
    title: 'Testing',
    description: 'No ingestion testing',
    scenario: 'Errors in production',
    impact: 'Risk',
    rootCause: 'No test pipeline',
    solution: 'Test framework',
    tools: 'PyTest, CI/CD',
  },
  {
    id: 34,
    title: 'DevOps Integration',
    description: 'No CI/CD for ingestion',
    scenario: 'Manual deployment',
    impact: 'Errors',
    rootCause: 'No automation',
    solution: 'CI/CD pipelines',
    tools: 'GitHub Actions',
  },
  {
    id: 35,
    title: 'Versioning',
    description: 'No pipeline version control',
    scenario: 'Changes not tracked',
    impact: 'Debug difficulty',
    rootCause: 'No versioning',
    solution: 'Git-based versioning',
    tools: 'Git',
  },
  {
    id: 36,
    title: 'Data Ownership',
    description: 'No owner for ingestion',
    scenario: 'Issues unresolved',
    impact: 'Accountability gap',
    rootCause: 'No ownership',
    solution: 'Assign owner',
    tools: 'Data governance',
  },
  {
    id: 37,
    title: 'Compliance',
    description: 'Regulatory violation',
    scenario: 'Sensitive data ingested wrongly',
    impact: 'Legal risk',
    rootCause: 'No compliance check',
    solution: 'Compliance validation',
    tools: 'GRC tools',
  },
  {
    id: 38,
    title: 'Third-party Data Risk',
    description: 'External data unreliable',
    scenario: 'Vendor data incorrect',
    impact: 'Bad analytics',
    rootCause: 'No validation',
    solution: 'Data validation',
    tools: 'Quality tools',
  },
  {
    id: 39,
    title: 'Latency Variability',
    description: 'Inconsistent ingestion time',
    scenario: 'Sometimes fast, sometimes slow',
    impact: 'Unpredictable SLA',
    rootCause: 'Resource contention',
    solution: 'Resource isolation',
    tools: 'Cluster config',
  },
  {
    id: 40,
    title: 'Scalability Limits',
    description: 'Cannot scale ingestion',
    scenario: 'Large spike fails system',
    impact: 'Downtime',
    rootCause: 'Static cluster',
    solution: 'Autoscaling',
    tools: 'Databricks',
  },
];

function IngestionChallenges() {
  return (
    <ChallengeLibrary
      pageTitle="Data Ingestion — 40 Challenges"
      pageSubtitle="Enterprise ingestion challenges with real scenarios, impact, root cause, solution, tools, and architect-level step-by-step guidance."
      statsLabel="Ingestion Challenges"
      totalCount={40}
      challenges={CHALLENGES}
      domain="ingestion"
      csvName="ingestion-challenges.csv"
    />
  );
}

export default IngestionChallenges;
