import React from 'react';
import ChallengeLibrary from '../../components/architect/ChallengeLibrary';

const CHALLENGES = [
  {
    id: 1,
    title: 'Data Structure Design',
    description: 'No clear model (star/snowflake)',
    scenario: 'Sales data stored as flat tables',
    impact: 'Poor query performance',
    rootCause: 'No modeling strategy',
    solution: 'Use star schema',
    tools: 'Delta Lake, dbt',
  },
  {
    id: 2,
    title: 'Normalization vs Denormalization',
    description: 'Over/under normalization',
    scenario: 'Highly normalized joins slow queries',
    impact: 'Performance issues',
    rootCause: 'Wrong design choice',
    solution: 'Balance normalization',
    tools: 'dbt, Spark',
  },
  {
    id: 3,
    title: 'Data Duplication',
    description: 'Same data stored multiple times',
    scenario: 'Customer data in multiple tables',
    impact: 'Inconsistency',
    rootCause: 'No master model',
    solution: 'Master data model',
    tools: 'MDM tools',
  },
  {
    id: 4,
    title: 'Data Consistency',
    description: 'Inconsistent values across tables',
    scenario: 'Different customer IDs',
    impact: 'Wrong reporting',
    rootCause: 'No standard keys',
    solution: 'Surrogate keys',
    tools: 'Delta Lake',
  },
  {
    id: 5,
    title: 'Key Management',
    description: 'No primary/foreign key strategy',
    scenario: 'Join failures',
    impact: 'Data mismatch',
    rootCause: 'No key design',
    solution: 'Define PK/FK strategy',
    tools: 'Spark SQL',
  },
  {
    id: 6,
    title: 'Slowly Changing Dimensions (SCD)',
    description: 'History not maintained',
    scenario: 'Customer address overwritten',
    impact: 'Loss of history',
    rootCause: 'No SCD design',
    solution: 'Implement SCD Type 2',
    tools: 'Delta MERGE',
  },
  {
    id: 7,
    title: 'Data Granularity',
    description: 'Wrong level of detail',
    scenario: 'Aggregated data only stored',
    impact: 'Cannot drill down',
    rootCause: 'Poor requirement analysis',
    solution: 'Define grain clearly',
    tools: 'Data modeling',
  },
  {
    id: 8,
    title: 'Schema Evolution',
    description: 'Model breaks on schema change',
    scenario: 'New fields added',
    impact: 'Pipeline failure',
    rootCause: 'Rigid schema',
    solution: 'Flexible schema design',
    tools: 'Delta Lake',
  },
  {
    id: 9,
    title: 'Data Quality in Modeling',
    description: 'Dirty data flows into silver/gold',
    scenario: 'Null or invalid fields',
    impact: 'Wrong KPIs',
    rootCause: 'Weak validation',
    solution: 'Data quality checks',
    tools: 'Great Expectations',
  },
  {
    id: 10,
    title: 'Business Logic Complexity',
    description: 'Complex transformations unclear',
    scenario: 'Pricing logic inconsistent',
    impact: 'Wrong metrics',
    rootCause: 'No logic standardization',
    solution: 'Central logic layer',
    tools: 'dbt',
  },
  {
    id: 11,
    title: 'Performance Optimization',
    description: 'Slow queries on gold layer',
    scenario: 'BI dashboards slow',
    impact: 'Poor UX',
    rootCause: 'No indexing/optimization',
    solution: 'Z-ORDER, caching',
    tools: 'Databricks Photon',
  },
  {
    id: 12,
    title: 'Partitioning Strategy',
    description: 'Wrong partition design',
    scenario: 'Large unpartitioned tables',
    impact: 'Slow queries',
    rootCause: 'No partition planning',
    solution: 'Partition on key columns',
    tools: 'Delta Lake',
  },
  {
    id: 13,
    title: 'Data Skew',
    description: 'Uneven data distribution',
    scenario: 'One partition overloaded',
    impact: 'Job failure',
    rootCause: 'Poor partitioning',
    solution: 'Repartitioning',
    tools: 'Spark',
  },
  {
    id: 14,
    title: 'Join Complexity',
    description: 'Too many joins',
    scenario: 'Multiple joins slow pipeline',
    impact: 'Latency',
    rootCause: 'Poor model design',
    solution: 'Optimize joins',
    tools: 'Spark SQL',
  },
  {
    id: 15,
    title: 'Data Lineage Missing',
    description: 'No transformation trace',
    scenario: 'Cannot track data flow',
    impact: 'Debug issues',
    rootCause: 'No lineage system',
    solution: 'Enable lineage tracking',
    tools: 'Unity Catalog',
  },
  {
    id: 16,
    title: 'Metadata Management',
    description: 'No schema documentation',
    scenario: 'Tables unclear',
    impact: 'Poor usability',
    rootCause: 'No catalog',
    solution: 'Metadata management',
    tools: 'Collibra',
  },
  {
    id: 17,
    title: 'Business Definition Mismatch',
    description: 'KPI definitions differ',
    scenario: 'Revenue calculated differently',
    impact: 'Confusion',
    rootCause: 'No semantic layer',
    solution: 'Semantic modeling',
    tools: 'dbt, BI tools',
  },
  {
    id: 18,
    title: 'Aggregation Errors',
    description: 'Wrong aggregation logic',
    scenario: 'Monthly totals incorrect',
    impact: 'Wrong reporting',
    rootCause: 'Logic errors',
    solution: 'Validation checks',
    tools: 'Spark',
  },
  {
    id: 19,
    title: 'Time Handling',
    description: 'Time dimension inconsistent',
    scenario: 'Different formats/timezones',
    impact: 'Wrong analysis',
    rootCause: 'No standard time handling',
    solution: 'Use UTC + time dimension',
    tools: 'Spark',
  },
  {
    id: 20,
    title: 'Data Freshness',
    description: 'Gold layer outdated',
    scenario: 'BI shows stale data',
    impact: 'Poor decisions',
    rootCause: 'Delay in pipeline',
    solution: 'Incremental load',
    tools: 'Delta',
  },
  {
    id: 21,
    title: 'Incremental Processing',
    description: 'Full load instead of incremental',
    scenario: 'Large data reload daily',
    impact: 'Cost + delay',
    rootCause: 'No incremental design',
    solution: 'CDC/incremental logic',
    tools: 'Delta MERGE',
  },
  {
    id: 22,
    title: 'Data Governance',
    description: 'No rules in modeling layer',
    scenario: 'Sensitive data exposed',
    impact: 'Compliance risk',
    rootCause: 'No governance enforcement',
    solution: 'Apply governance rules',
    tools: 'Unity Catalog',
  },
  {
    id: 23,
    title: 'Access Control',
    description: 'No role-based access',
    scenario: 'Users see restricted data',
    impact: 'Security issue',
    rootCause: 'Weak IAM',
    solution: 'RBAC',
    tools: 'Unity Catalog',
  },
  {
    id: 24,
    title: 'Testing',
    description: 'No model testing',
    scenario: 'Errors reach production',
    impact: 'Risk',
    rootCause: 'No test framework',
    solution: 'Unit/data tests',
    tools: 'dbt tests',
  },
  {
    id: 25,
    title: 'Version Control',
    description: 'Model changes not tracked',
    scenario: 'Breaking changes',
    impact: 'Debug issues',
    rootCause: 'No versioning',
    solution: 'Git-based versioning',
    tools: 'Git',
  },
  {
    id: 26,
    title: 'Reusability',
    description: 'Duplicate transformation logic',
    scenario: 'Same logic in multiple pipelines',
    impact: 'Maintenance overhead',
    rootCause: 'No reusable layer',
    solution: 'Shared models',
    tools: 'dbt',
  },
  {
    id: 27,
    title: 'Data Explosion',
    description: 'Too many tables/views',
    scenario: 'Hard to manage',
    impact: 'Complexity',
    rootCause: 'Poor design',
    solution: 'Layered architecture',
    tools: 'Lakehouse',
  },
  {
    id: 28,
    title: 'Late Data Handling',
    description: 'Late data not merged correctly',
    scenario: 'Missing transactions',
    impact: 'Incomplete data',
    rootCause: 'No late handling',
    solution: 'Upsert logic',
    tools: 'Delta',
  },
  {
    id: 29,
    title: 'Data Drift',
    description: 'Business patterns change',
    scenario: 'Model outdated',
    impact: 'Wrong predictions',
    rootCause: 'No monitoring',
    solution: 'Drift detection',
    tools: 'Monitoring tools',
  },
  {
    id: 30,
    title: 'Performance vs Cost',
    description: 'Over-optimization increases cost',
    scenario: 'Heavy compute for speed',
    impact: 'High cost',
    rootCause: 'No balance',
    solution: 'Optimize cost-performance',
    tools: 'FinOps',
  },
  {
    id: 31,
    title: 'Multi-source Integration',
    description: 'Different sources not aligned',
    scenario: 'ERP vs CRM mismatch',
    impact: 'Inconsistent model',
    rootCause: 'No mapping strategy',
    solution: 'Canonical model',
    tools: 'ETL',
  },
  {
    id: 32,
    title: 'Semantic Layer Missing',
    description: 'No business-friendly layer',
    scenario: 'Users query raw tables',
    impact: 'Errors',
    rootCause: 'No abstraction',
    solution: 'Semantic layer',
    tools: 'Power BI, dbt',
  },
  {
    id: 33,
    title: 'Hardcoded Logic',
    description: 'Logic embedded in code',
    scenario: 'Difficult to update',
    impact: 'Maintenance issue',
    rootCause: 'Poor design',
    solution: 'Parameterized logic',
    tools: 'dbt',
  },
  {
    id: 34,
    title: 'Data Ownership',
    description: 'No owner for model',
    scenario: 'Issues unresolved',
    impact: 'Accountability gap',
    rootCause: 'No governance',
    solution: 'Assign owner',
    tools: 'Data governance',
  },
  {
    id: 35,
    title: 'Pipeline Dependency',
    description: 'Model depends on upstream failure',
    scenario: 'Cascade failure',
    impact: 'Delay',
    rootCause: 'No orchestration',
    solution: 'Workflow control',
    tools: 'Airflow',
  },
  {
    id: 36,
    title: 'Model Documentation',
    description: 'No documentation',
    scenario: 'Hard to understand model',
    impact: 'Low adoption',
    rootCause: 'No documentation',
    solution: 'Data docs',
    tools: 'dbt docs',
  },
  {
    id: 37,
    title: 'Auditability',
    description: 'No tracking of changes',
    scenario: 'Cannot audit model changes',
    impact: 'Compliance issue',
    rootCause: 'No logs',
    solution: 'Audit logs',
    tools: 'Unity Catalog',
  },
  {
    id: 38,
    title: 'Model Reconciliation',
    description: 'No validation vs source',
    scenario: 'Data mismatch',
    impact: 'Trust issue',
    rootCause: 'No reconciliation',
    solution: 'Reconciliation checks',
    tools: 'Spark',
  },
  {
    id: 39,
    title: 'Scalability',
    description: 'Model fails at scale',
    scenario: 'Large joins fail',
    impact: 'System crash',
    rootCause: 'Poor design',
    solution: 'Distributed modeling',
    tools: 'Spark',
  },
  {
    id: 40,
    title: 'AI Readiness',
    description: 'Model not usable for ML',
    scenario: 'Features not structured',
    impact: 'ML failure',
    rootCause: 'No feature engineering',
    solution: 'Feature store',
    tools: 'Databricks Feature Store',
  },
];

function ModelingChallenges() {
  return (
    <ChallengeLibrary
      pageTitle="Data Modeling — 40 Challenges"
      pageSubtitle="Enterprise modeling challenges (grain, SCD, partitioning, semantic layer) with step-by-step architect guidance."
      statsLabel="Modeling Challenges"
      totalCount={40}
      challenges={CHALLENGES}
      domain="modeling"
      csvName="modeling-challenges.csv"
    />
  );
}

export default ModelingChallenges;
