import React from 'react';
import ImplementationLibrary from '../../components/architect/ImplementationLibrary';

const ROWS = [
  {
    id: 1,
    topic: 'Modeling Strategy',
    definition: 'Define target modeling approach',
    implementation: 'Choose medallion + star schema / dimensional model',
    task: 'Assess reporting and analytics needs',
    service: 'Databricks',
    deliverable: 'Modeling strategy document',
    validation: 'Stakeholder review',
    testing: 'Design review test',
    comparison: 'Star vs Snowflake vs Wide table',
    deployment: 'Version-controlled rollout',
    flow: 'Bronze → Silver → Gold',
  },
  {
    id: 2,
    topic: 'Silver Layer Design',
    definition: 'Define conformed clean layer',
    implementation: 'Standardize entities, datatypes, keys',
    task: 'Build reusable silver tables',
    service: 'Delta Lake',
    deliverable: 'Silver schema',
    validation: 'Schema and business review',
    testing: 'Unit and integration tests',
    comparison: 'Raw vs conformed',
    deployment: 'CI/CD deployment',
    flow: 'Bronze → Silver',
  },
  {
    id: 3,
    topic: 'Gold Layer Design',
    definition: 'Define business-ready layer',
    implementation: 'Build marts, KPI tables, aggregates',
    task: 'Create domain-specific gold datasets',
    service: 'Databricks SQL',
    deliverable: 'Gold tables/views',
    validation: 'Business validation',
    testing: 'UAT',
    comparison: 'Silver vs Gold',
    deployment: 'Release pipeline',
    flow: 'Silver → Gold',
  },
  {
    id: 4,
    topic: 'Entity Standardization',
    definition: 'Align business entities',
    implementation: 'Standard naming, structure, and field definitions',
    task: 'Normalize customer, product, order entities',
    service: 'Spark SQL',
    deliverable: 'Standardized entity tables',
    validation: 'Domain sign-off',
    testing: 'Data consistency tests',
    comparison: 'Source-specific vs canonical',
    deployment: 'Controlled deployment',
    flow: 'Source entities → Canonical',
  },
  {
    id: 5,
    topic: 'Key Design',
    definition: 'Define join and surrogate keys',
    implementation: 'Create business keys and surrogate keys',
    task: 'Implement key generation rules',
    service: 'Spark / Delta',
    deliverable: 'Key mapping logic',
    validation: 'Join accuracy validation',
    testing: 'Referential integrity tests',
    comparison: 'Natural vs surrogate keys',
    deployment: 'Automated pipeline',
    flow: 'Source keys → Model keys',
  },
  {
    id: 6,
    topic: 'Deduplication',
    definition: 'Remove duplicate business records',
    implementation: 'Business-key-based dedup in silver',
    task: 'Apply latest-record or trusted-record rules',
    service: 'Delta Lake',
    deliverable: 'Deduplicated tables',
    validation: 'Row count and uniqueness validation',
    testing: 'Duplicate tests',
    comparison: 'Append-only vs deduped',
    deployment: 'Scheduled jobs',
    flow: 'Bronze → Silver clean',
  },
  {
    id: 7,
    topic: 'Slowly Changing Dimensions',
    definition: 'Maintain historical attributes',
    implementation: 'Implement SCD Type 1/2 logic',
    task: 'Track changes for customer/product',
    service: 'Delta MERGE',
    deliverable: 'Historical dimension table',
    validation: 'History validation',
    testing: 'SCD tests',
    comparison: 'Overwrite vs history',
    deployment: 'Automated model deployment',
    flow: 'Updates → Dimension history',
  },
  {
    id: 8,
    topic: 'Business Rule Layer',
    definition: 'Centralize transformation logic',
    implementation: 'Apply pricing, tax, contract, status logic',
    task: 'Build reusable logic in SQL/notebooks/dbt',
    service: 'Databricks SQL / dbt',
    deliverable: 'Business rules repository',
    validation: 'Business approval',
    testing: 'Rule regression tests',
    comparison: 'Embedded BI logic vs centralized',
    deployment: 'CI/CD',
    flow: 'Silver → Gold logic',
  },
  {
    id: 9,
    topic: 'Join Strategy',
    definition: 'Optimize data relationships',
    implementation: 'Define join patterns and conformed grain',
    task: 'Build performant joins across domains',
    service: 'Spark SQL',
    deliverable: 'Joined conformed tables',
    validation: 'Reconciliation validation',
    testing: 'Join logic tests',
    comparison: 'Large shuffle vs optimized join',
    deployment: 'Managed rollout',
    flow: 'Multi-source → Conformed dataset',
  },
  {
    id: 10,
    topic: 'Grain Definition',
    definition: 'Define level of detail',
    implementation: 'Establish transaction, daily, monthly grain',
    task: 'Document table granularity',
    service: 'Databricks',
    deliverable: 'Grain specification',
    validation: 'Business sign-off',
    testing: 'Aggregation tests',
    comparison: 'Mixed grain vs explicit grain',
    deployment: 'Metadata deployment',
    flow: 'Detailed → Aggregated',
  },
  {
    id: 11,
    topic: 'Time Dimension',
    definition: 'Standardize date/time analysis',
    implementation: 'Build calendar and fiscal dimensions',
    task: 'Support YoY, MoM, period comparisons',
    service: 'Spark SQL',
    deliverable: 'Time dimension table',
    validation: 'Business calendar validation',
    testing: 'Time logic tests',
    comparison: 'Ad hoc date logic vs time dimension',
    deployment: 'Release-managed',
    flow: 'Dates → Time analytics',
  },
  {
    id: 12,
    topic: 'Data Quality in Modeling',
    definition: 'Enforce trust in modeled data',
    implementation: 'Apply null, range, uniqueness, referential checks',
    task: 'Add quality gates in silver/gold',
    service: 'Great Expectations / dbt',
    deliverable: 'Data quality report',
    validation: 'Threshold validation',
    testing: 'DQ tests',
    comparison: 'No checks vs governed checks',
    deployment: 'Integrated deployment',
    flow: 'Model → Quality gate',
  },
  {
    id: 13,
    topic: 'Semantic KPI Layer',
    definition: 'Standardize KPI definitions',
    implementation: 'Centralize measures in gold/semantic layer',
    task: 'Define revenue, margin, churn, etc.',
    service: 'dbt / Databricks SQL',
    deliverable: 'KPI definitions catalog',
    validation: 'Business validation',
    testing: 'KPI regression tests',
    comparison: 'KPI in BI vs KPI in model',
    deployment: 'Controlled promotion',
    flow: 'Gold → BI semantic use',
  },
  {
    id: 14,
    topic: 'Aggregation Strategy',
    definition: 'Optimize analytical performance',
    implementation: 'Create summary tables/materialized views',
    task: 'Build daily, weekly, monthly aggregates',
    service: 'Databricks SQL',
    deliverable: 'Aggregated marts',
    validation: 'Reconciliation to detail',
    testing: 'Aggregation accuracy tests',
    comparison: 'Raw query vs pre-aggregated',
    deployment: 'Scheduled refresh',
    flow: 'Detail → Summary',
  },
  {
    id: 15,
    topic: 'Partitioning and Clustering',
    definition: 'Optimize storage and query patterns',
    implementation: 'Partition by date/domain and optimize layout',
    task: 'Improve performance of silver/gold reads',
    service: 'Delta Lake',
    deliverable: 'Optimized model tables',
    validation: 'Query plan review',
    testing: 'Performance tests',
    comparison: 'Partitioned vs unpartitioned',
    deployment: 'Managed optimization',
    flow: 'Stored model → Fast query',
  },
  {
    id: 16,
    topic: 'Data Lineage in Modeling',
    definition: 'Trace transformation flow',
    implementation: 'Capture source-to-model lineage',
    task: 'Enable column/table lineage',
    service: 'Unity Catalog',
    deliverable: 'Lineage graph',
    validation: 'Lineage review',
    testing: 'Audit tests',
    comparison: 'Manual trace vs automated lineage',
    deployment: 'Auto-enabled',
    flow: 'Bronze → Gold traceability',
  },
  {
    id: 17,
    topic: 'Metadata and Documentation',
    definition: 'Document modeled assets',
    implementation: 'Create descriptions, owners, grain, KPI notes',
    task: 'Publish docs for silver/gold',
    service: 'Unity Catalog / dbt docs',
    deliverable: 'Data dictionary',
    validation: 'Metadata completeness check',
    testing: 'Documentation review',
    comparison: 'Undocumented vs documented',
    deployment: 'Continuous publishing',
    flow: 'Model → Catalog',
  },
  {
    id: 18,
    topic: 'Access Control on Modeled Data',
    definition: 'Secure business datasets',
    implementation: 'Apply RBAC/RLS/CLS where needed',
    task: 'Restrict sensitive modeled data',
    service: 'Unity Catalog',
    deliverable: 'Access policy set',
    validation: 'Permission validation',
    testing: 'Security tests',
    comparison: 'Open vs governed access',
    deployment: 'Policy deployment',
    flow: 'Gold → Authorized consumption',
  },
  {
    id: 19,
    topic: 'Reconciliation Framework',
    definition: 'Match model output with source truth',
    implementation: 'Compare source totals to modeled outputs',
    task: 'Build reconciliation reports',
    service: 'Spark / SQL',
    deliverable: 'Reconciliation dashboard',
    validation: 'Tolerance checks',
    testing: 'Regression tests',
    comparison: 'No recon vs controlled recon',
    deployment: 'Automated workflow',
    flow: 'Source → Model accuracy',
  },
  {
    id: 20,
    topic: 'Incremental Modeling',
    definition: 'Avoid full refresh when possible',
    implementation: 'Use MERGE, CDC, watermark logic',
    task: 'Process only changed data',
    service: 'Delta Lake',
    deliverable: 'Incremental model pipeline',
    validation: 'Delta validation',
    testing: 'Incremental tests',
    comparison: 'Full refresh vs incremental',
    deployment: 'Scheduled orchestration',
    flow: 'Changes → Updated model',
  },
  {
    id: 21,
    topic: 'Error Handling in Modeling',
    definition: 'Handle transformation failures safely',
    implementation: 'Quarantine bad joins/records',
    task: 'Implement exception flows',
    service: 'Databricks Workflows',
    deliverable: 'Exception tables/logs',
    validation: 'Error count validation',
    testing: 'Failure scenario tests',
    comparison: 'Fail-fast vs controlled exception handling',
    deployment: 'Automated jobs',
    flow: 'Model → Exception path',
  },
  {
    id: 22,
    topic: 'Performance Optimization',
    definition: 'Tune transformation workloads',
    implementation: 'Broadcast joins, AQE, Z-ORDER, caching',
    task: 'Reduce runtime and compute cost',
    service: 'Spark / Photon',
    deliverable: 'Tuned pipelines',
    validation: 'Performance benchmark',
    testing: 'Load tests',
    comparison: 'Default vs tuned execution',
    deployment: 'Config-managed rollout',
    flow: 'Slow model → Optimized model',
  },
  {
    id: 23,
    topic: 'Reusability and Modular Design',
    definition: 'Avoid repeated logic',
    implementation: 'Create reusable model components/macros',
    task: 'Share dimensions and transformations',
    service: 'dbt / notebooks',
    deliverable: 'Reusable modules',
    validation: 'Code review',
    testing: 'Regression tests',
    comparison: 'Duplicated logic vs modular',
    deployment: 'CI/CD',
    flow: 'Shared logic → Multiple models',
  },
  {
    id: 24,
    topic: 'CI/CD for Models',
    definition: 'Automate model changes',
    implementation: 'Git-based deployments for SQL/notebooks/dbt',
    task: 'Promote Dev → QA → Prod',
    service: 'GitHub Actions / Azure DevOps',
    deliverable: 'Model deployment pipeline',
    validation: 'Build validation',
    testing: 'Deployment tests',
    comparison: 'Manual vs automated release',
    deployment: 'Continuous deployment',
    flow: 'Code → Modeled tables',
  },
  {
    id: 25,
    topic: 'Monitoring and SLA',
    definition: 'Track model freshness and health',
    implementation: 'Monitor run times, failures, staleness',
    task: 'Configure alerts and dashboards',
    service: 'Datadog / Azure Monitor',
    deliverable: 'Model ops dashboard',
    validation: 'SLA validation',
    testing: 'Alert tests',
    comparison: 'Reactive vs monitored',
    deployment: 'Continuous ops',
    flow: 'Model refresh → Monitoring',
  },
  {
    id: 26,
    topic: 'Auditability',
    definition: 'Preserve model decision evidence',
    implementation: 'Track logic/version changes and approvals',
    task: 'Maintain change history',
    service: 'Git / UC / ADRs',
    deliverable: 'Audit trail',
    validation: 'Audit review',
    testing: 'Compliance tests',
    comparison: 'Untracked vs versioned',
    deployment: 'Controlled change deployment',
    flow: 'Change → Evidence',
  },
  {
    id: 27,
    topic: 'AI/ML Readiness',
    definition: 'Make models usable for ML/GenAI',
    implementation: 'Build feature-ready and retrieval-ready datasets',
    task: 'Support feature store / RAG contexts',
    service: 'Databricks Feature Store',
    deliverable: 'Feature-ready tables',
    validation: 'Feature validation',
    testing: 'ML pipeline tests',
    comparison: 'BI-only vs AI-ready modeling',
    deployment: 'Managed rollout',
    flow: 'Gold → AI consumption',
  },
  {
    id: 28,
    topic: 'Governance Alignment',
    definition: 'Align model with enterprise controls',
    implementation: 'Apply ownership, standards, retention',
    task: 'Integrate with data governance process',
    service: 'Unity Catalog / Collibra',
    deliverable: 'Governed model inventory',
    validation: 'Governance review',
    testing: 'Policy tests',
    comparison: 'Isolated modeling vs governed',
    deployment: 'Policy-controlled',
    flow: 'Model → Governed asset',
  },
  {
    id: 29,
    topic: 'Cost Optimization',
    definition: 'Balance performance and spend',
    implementation: 'Tune cluster, refresh cadence, storage layout',
    task: 'Reduce cost of transformations',
    service: 'FinOps + Databricks',
    deliverable: 'Cost optimization plan',
    validation: 'Cost trend validation',
    testing: 'Cost-performance tests',
    comparison: 'Max performance vs balanced design',
    deployment: 'Managed deployment',
    flow: 'Model ops → Cost control',
  },
  {
    id: 30,
    topic: 'Business Consumption Readiness',
    definition: 'Prepare model for BI users',
    implementation: 'Publish stable tables/views with naming standards',
    task: 'Support dashboards and self-service',
    service: 'Databricks SQL / Power BI',
    deliverable: 'Certified gold datasets',
    validation: 'Business acceptance',
    testing: 'UAT',
    comparison: 'Raw access vs curated consumption',
    deployment: 'Certified release',
    flow: 'Gold → Reporting',
  },
];

export default function ModelingImplementation() {
  return (
    <ImplementationLibrary
      pageTitle="Data Modeling — Enterprise Implementation"
      pageSubtitle="30 end-to-end modeling patterns covering medallion layers, SCD, semantic KPI layer, governance alignment, and AI readiness."
      statsLabel="Modeling Topics"
      rows={ROWS}
      csvName="modeling-implementation.csv"
      accent="#8b5cf6"
    />
  );
}
