import React from 'react';
import ImplementationLibrary from '../../components/architect/ImplementationLibrary';

const ROWS = [
  {
    id: 1,
    topic: 'Visualization Strategy',
    definition: 'Define reporting and dashboard approach',
    implementation: 'Select BI pattern for executive, operational, and self-service reporting',
    task: 'Align reporting needs with business roles',
    service: 'Power BI / Tableau / Databricks SQL',
    deliverable: 'Visualization strategy document',
    validation: 'Stakeholder sign-off',
    testing: 'Design review',
    comparison: 'Static reports vs interactive dashboards',
    deployment: 'Controlled rollout',
    flow: 'Gold → BI',
  },
  {
    id: 2,
    topic: 'Consumption Model',
    definition: 'Define how users consume data',
    implementation: 'DirectQuery, import, extracts, or semantic layer access',
    task: 'Choose access mode per use case',
    service: 'BI platform',
    deliverable: 'Consumption design',
    validation: 'Architecture validation',
    testing: 'Connectivity tests',
    comparison: 'Import vs DirectQuery',
    deployment: 'Environment-based deployment',
    flow: 'Gold → Semantic → BI',
  },
  {
    id: 3,
    topic: 'Semantic Layer Design',
    definition: 'Create reusable business abstraction',
    implementation: 'Build certified metrics, dimensions, hierarchies, and measures',
    task: 'Define reusable KPI model',
    service: 'Power BI / dbt / Databricks SQL',
    deliverable: 'Semantic dataset',
    validation: 'KPI validation',
    testing: 'Metric regression tests',
    comparison: 'KPI in dashboard vs centralized semantic layer',
    deployment: 'Managed promotion',
    flow: 'Gold → Semantic layer',
  },
  {
    id: 4,
    topic: 'KPI Standardization',
    definition: 'Standardize core business metrics',
    implementation: 'Centralize revenue, margin, churn, utilization logic',
    task: 'Define KPI rules and ownership',
    service: 'Semantic model / dbt',
    deliverable: 'KPI catalog',
    validation: 'Business sign-off',
    testing: 'Cross-report consistency tests',
    comparison: 'Different tool logic vs one KPI definition',
    deployment: 'Certified release',
    flow: 'Logic → KPI',
  },
  {
    id: 5,
    topic: 'Dataset Certification',
    definition: 'Publish trusted datasets',
    implementation: 'Mark approved datasets for business use',
    task: 'Certify curated data products',
    service: 'BI platform / Databricks SQL',
    deliverable: 'Certified datasets',
    validation: 'Governance validation',
    testing: 'Access and accuracy tests',
    comparison: 'Open datasets vs certified datasets',
    deployment: 'Controlled publishing',
    flow: 'Gold → Certified dataset',
  },
  {
    id: 6,
    topic: 'Data Model for BI',
    definition: 'Optimize analytical relationships',
    implementation: 'Build star schema / denormalized marts for reporting',
    task: 'Structure fact-dimension model',
    service: 'Databricks SQL / Power BI',
    deliverable: 'BI-optimized model',
    validation: 'Query and join validation',
    testing: 'Model tests',
    comparison: 'Raw tables vs BI model',
    deployment: 'Release pipeline',
    flow: 'Gold → BI model',
  },
  {
    id: 7,
    topic: 'Dashboard Design',
    definition: 'Build visual interface for decisions',
    implementation: 'Use layout, filters, drill paths, summaries',
    task: 'Design executive and operational dashboards',
    service: 'Power BI / Tableau',
    deliverable: 'Dashboard mockups and reports',
    validation: 'UX review',
    testing: 'UAT',
    comparison: 'Ad hoc visuals vs design standard',
    deployment: 'BI deployment',
    flow: 'Semantic layer → Dashboard',
  },
  {
    id: 8,
    topic: 'Role-Based Dashboarding',
    definition: 'Tailor views by audience',
    implementation: 'Create executive, manager, analyst dashboards',
    task: 'Map views to personas',
    service: 'BI platform',
    deliverable: 'Role-based reports',
    validation: 'Stakeholder approval',
    testing: 'Access tests',
    comparison: 'One dashboard for all vs role-based design',
    deployment: 'Controlled publishing',
    flow: 'Role → Dashboard',
  },
  {
    id: 9,
    topic: 'Drill-Down and Navigation',
    definition: 'Enable deeper analysis',
    implementation: 'Add drill-through, hierarchy navigation, linked detail views',
    task: 'Configure interactive paths',
    service: 'Power BI / Tableau',
    deliverable: 'Drill-ready dashboards',
    validation: 'Functional validation',
    testing: 'Navigation tests',
    comparison: 'Static vs drillable reports',
    deployment: 'BI release',
    flow: 'Summary → Detail',
  },
  {
    id: 10,
    topic: 'Time Intelligence',
    definition: 'Support period analysis',
    implementation: 'Add YoY, MoM, QTD, YTD calculations',
    task: 'Implement calendar-aware measures',
    service: 'Semantic model / BI tool',
    deliverable: 'Time analytics report',
    validation: 'Business validation',
    testing: 'Time logic tests',
    comparison: 'Manual calculations vs standard time intelligence',
    deployment: 'Release-managed',
    flow: 'Date model → KPI trend',
  },
  {
    id: 11,
    topic: 'Data Refresh Strategy',
    definition: 'Keep dashboards current',
    implementation: 'Schedule refresh, near real-time, or live queries',
    task: 'Configure refresh cadence',
    service: 'Power BI gateway / Databricks SQL',
    deliverable: 'Refresh configuration',
    validation: 'Freshness validation',
    testing: 'Refresh failure tests',
    comparison: 'Daily batch vs near real-time',
    deployment: 'Scheduled deployment',
    flow: 'Gold refresh → BI refresh',
  },
  {
    id: 12,
    topic: 'Performance Optimization',
    definition: 'Improve dashboard responsiveness',
    implementation: 'Use aggregates, query tuning, caching, optimized gold tables',
    task: 'Reduce load time and scan cost',
    service: 'Databricks SQL / BI engine',
    deliverable: 'Optimized report',
    validation: 'Performance benchmark',
    testing: 'Load tests',
    comparison: 'Untuned vs tuned dashboard',
    deployment: 'Continuous optimization',
    flow: 'Query → Fast response',
  },
  {
    id: 13,
    topic: 'Query Governance',
    definition: 'Control expensive or unsafe queries',
    implementation: 'Use optimized views, warehouse sizing, and query patterns',
    task: 'Prevent runaway BI workloads',
    service: 'Databricks SQL warehouse',
    deliverable: 'Query governance rules',
    validation: 'Runtime validation',
    testing: 'Concurrency tests',
    comparison: 'Direct raw queries vs governed access',
    deployment: 'Policy rollout',
    flow: 'BI query → Controlled execution',
  },
  {
    id: 14,
    topic: 'Row-Level Security',
    definition: 'Restrict data by user context',
    implementation: 'Apply user, region, business-unit filters',
    task: 'Enforce contextual access',
    service: 'Power BI / Unity Catalog / Tableau',
    deliverable: 'Secured report access',
    validation: 'Access validation',
    testing: 'Security tests',
    comparison: 'Open reports vs RLS-enabled',
    deployment: 'Policy deployment',
    flow: 'User → Filtered data',
  },
  {
    id: 15,
    topic: 'Column-Level Protection',
    definition: 'Hide sensitive fields in reports',
    implementation: 'Mask financial or personal fields',
    task: 'Enforce secure visibility',
    service: 'Unity Catalog / BI tool',
    deliverable: 'Protected views',
    validation: 'Masking validation',
    testing: 'Security tests',
    comparison: 'Full visibility vs protected reporting',
    deployment: 'Controlled release',
    flow: 'Data → Protected report',
  },
  {
    id: 16,
    topic: 'Report Sharing Model',
    definition: 'Define how reports are distributed',
    implementation: 'Workspace, app, secure share, embedded access',
    task: 'Set delivery pattern',
    service: 'Power BI service / Tableau server',
    deliverable: 'Sharing model',
    validation: 'Access review',
    testing: 'Sharing tests',
    comparison: 'Uncontrolled sharing vs managed distribution',
    deployment: 'Workspace/app deployment',
    flow: 'Report → Consumer',
  },
  {
    id: 17,
    topic: 'Self-Service Analytics Enablement',
    definition: 'Support governed business exploration',
    implementation: 'Publish curated datasets and business fields',
    task: 'Enable trusted self-service',
    service: 'Power BI / Tableau / Databricks SQL',
    deliverable: 'Self-service dataset package',
    validation: 'Adoption validation',
    testing: 'Usability tests',
    comparison: 'Raw access vs governed self-service',
    deployment: 'Certified rollout',
    flow: 'Dataset → User exploration',
  },
  {
    id: 18,
    topic: 'Visualization Standards',
    definition: 'Standardize report design',
    implementation: 'Define layout, colors, naming, KPI placement',
    task: 'Create reusable templates',
    service: 'BI governance',
    deliverable: 'Dashboard standards',
    validation: 'UX validation',
    testing: 'Template tests',
    comparison: 'Inconsistent visuals vs standard design system',
    deployment: 'Template rollout',
    flow: 'Standard → Report',
  },
  {
    id: 19,
    topic: 'Alerting and Subscriptions',
    definition: 'Notify users of KPI changes',
    implementation: 'Configure threshold alerts and scheduled subscriptions',
    task: 'Enable proactive reporting',
    service: 'Power BI / BI tool',
    deliverable: 'Alert rules and subscriptions',
    validation: 'Alert validation',
    testing: 'Notification tests',
    comparison: 'Manual checking vs alert-driven usage',
    deployment: 'Feature deployment',
    flow: 'KPI → Alert',
  },
  {
    id: 20,
    topic: 'Reconciliation to Source',
    definition: 'Prove report accuracy',
    implementation: 'Compare dashboard totals with gold/source truth',
    task: 'Build report reconciliation process',
    service: 'SQL / Databricks',
    deliverable: 'Reconciliation report',
    validation: 'Tolerance validation',
    testing: 'Regression tests',
    comparison: 'Trust by assumption vs verified reporting',
    deployment: 'Automated checks',
    flow: 'Source → Dashboard accuracy',
  },
  {
    id: 21,
    topic: 'BI Metadata and Documentation',
    definition: 'Document report purpose and logic',
    implementation: 'Describe metrics, owners, refresh cadence, lineage',
    task: 'Publish BI metadata',
    service: 'Catalog / BI platform',
    deliverable: 'Report documentation',
    validation: 'Completeness review',
    testing: 'Documentation tests',
    comparison: 'Undocumented vs discoverable reporting',
    deployment: 'Continuous publishing',
    flow: 'Report → Metadata',
  },
  {
    id: 22,
    topic: 'Lineage to BI',
    definition: 'Trace report back to source',
    implementation: 'Connect KPI/report lineage to gold tables and transformations',
    task: 'Enable source-to-visual traceability',
    service: 'Unity Catalog / BI lineage',
    deliverable: 'BI lineage map',
    validation: 'Lineage validation',
    testing: 'Audit tests',
    comparison: 'Broken trace vs end-to-end trace',
    deployment: 'Auto-enabled',
    flow: 'Source → KPI → Dashboard',
  },
  {
    id: 23,
    topic: 'Dashboard Testing',
    definition: 'Validate report correctness',
    implementation: 'Test filters, measures, visuals, drill paths',
    task: 'Build QA suite for BI assets',
    service: 'BI tool / QA process',
    deliverable: 'Test cases and QA sign-off',
    validation: 'UAT validation',
    testing: 'Functional, regression tests',
    comparison: 'Visual-only review vs structured testing',
    deployment: 'Release process',
    flow: 'Build → Validate',
  },
  {
    id: 24,
    topic: 'Accessibility and Usability',
    definition: 'Ensure reports are usable',
    implementation: 'Design for readability, accessibility, mobile use',
    task: 'Improve adoption and compliance',
    service: 'BI platform',
    deliverable: 'Accessible dashboard set',
    validation: 'UX review',
    testing: 'Accessibility tests',
    comparison: 'Desktop-only vs inclusive design',
    deployment: 'BI release',
    flow: 'Report → End user',
  },
  {
    id: 25,
    topic: 'Mobile Reporting',
    definition: 'Support mobile users',
    implementation: 'Create responsive layouts and compact views',
    task: 'Design mobile-friendly reporting',
    service: 'Power BI / Tableau',
    deliverable: 'Mobile dashboards',
    validation: 'Mobile validation',
    testing: 'Device tests',
    comparison: 'Web-only vs multi-device reporting',
    deployment: 'Mobile publish',
    flow: 'Dashboard → Mobile',
  },
  {
    id: 26,
    topic: 'Monitoring BI Usage',
    definition: 'Track adoption and usage quality',
    implementation: 'Measure active users, slow reports, failures',
    task: 'Build BI ops dashboard',
    service: 'BI admin tools / Datadog',
    deliverable: 'Usage dashboard',
    validation: 'Metric validation',
    testing: 'Alert tests',
    comparison: 'No visibility vs monitored adoption',
    deployment: 'Continuous monitoring',
    flow: 'Usage → Insight',
  },
  {
    id: 27,
    topic: 'BI Incident Handling',
    definition: 'Manage report outages/issues',
    implementation: 'Define refresh failure, slow report, access failure process',
    task: 'Implement BI support workflow',
    service: 'BI ops / ticketing',
    deliverable: 'Incident playbook',
    validation: 'Process validation',
    testing: 'Simulation tests',
    comparison: 'Reactive fix vs structured support',
    deployment: 'Ops rollout',
    flow: 'BI issue → Resolution',
  },
  {
    id: 28,
    topic: 'Cost Optimization for BI',
    definition: 'Control query and refresh cost',
    implementation: 'Tune refresh frequency, warehouse size, extracts',
    task: 'Reduce BI operating cost',
    service: 'Databricks SQL / FinOps',
    deliverable: 'BI cost plan',
    validation: 'Cost validation',
    testing: 'Cost-performance tests',
    comparison: 'Max freshness vs balanced cost',
    deployment: 'Config-managed rollout',
    flow: 'BI workload → Cost control',
  },
  {
    id: 29,
    topic: 'Governance Alignment',
    definition: 'Align BI with governance rules',
    implementation: 'Use certified datasets, secure views, report approvals',
    task: 'Prevent report sprawl and metric drift',
    service: 'Unity Catalog / BI governance',
    deliverable: 'Governed BI model',
    validation: 'Governance validation',
    testing: 'Policy tests',
    comparison: 'Open BI sprawl vs governed BI',
    deployment: 'Controlled publishing',
    flow: 'Governance → BI',
  },
  {
    id: 30,
    topic: 'Business Adoption and Enablement',
    definition: 'Drive real usage and trust',
    implementation: 'Train users, document semantics, provide support model',
    task: 'Improve business adoption',
    service: 'BI platform / training',
    deliverable: 'Adoption plan',
    validation: 'Stakeholder review',
    testing: 'Adoption feedback tests',
    comparison: 'Dashboards built vs dashboards used',
    deployment: 'Phased rollout',
    flow: 'Dashboard → Decision-making',
  },
];

export default function VisualizationImplementation() {
  return (
    <ImplementationLibrary
      pageTitle="Data Visualization — Enterprise Implementation"
      pageSubtitle="30 visualization patterns covering semantic layer, KPI standards, dashboard design, RLS, governance, and adoption."
      statsLabel="Visualization Topics"
      rows={ROWS}
      csvName="visualization-implementation.csv"
      accent="#ec4899"
    />
  );
}
