import React from 'react';
import ChallengeLibrary from '../../components/architect/ChallengeLibrary';

const CHALLENGES = [
  {
    id: 1,
    title: 'Performance',
    description: 'Slow dashboards',
    scenario: 'Power BI report takes 20 sec to load',
    impact: 'Poor UX',
    rootCause: 'Heavy queries, no aggregation',
    solution: 'Pre-aggregated gold tables',
    tools: 'Power BI, Databricks SQL',
  },
  {
    id: 2,
    title: 'Data Latency',
    description: 'Outdated data',
    scenario: "Dashboard shows yesterday's data",
    impact: 'Wrong decisions',
    rootCause: 'Batch-only pipelines',
    solution: 'Near real-time refresh',
    tools: 'Streaming, DirectQuery',
  },
  {
    id: 3,
    title: 'Data Accuracy',
    description: 'Wrong numbers',
    scenario: 'Revenue mismatch across reports',
    impact: 'Loss of trust',
    rootCause: 'No validation',
    solution: 'Data reconciliation',
    tools: 'dbt, Spark',
  },
  {
    id: 4,
    title: 'Semantic Layer',
    description: 'No business layer',
    scenario: 'Users query raw tables',
    impact: 'Confusion',
    rootCause: 'No abstraction',
    solution: 'Semantic model',
    tools: 'Power BI model, dbt',
  },
  {
    id: 5,
    title: 'KPI Definition',
    description: 'Inconsistent metrics',
    scenario: 'Revenue differs across teams',
    impact: 'Misalignment',
    rootCause: 'No standard definition',
    solution: 'KPI standardization',
    tools: 'Business glossary',
  },
  {
    id: 6,
    title: 'Data Modeling for BI',
    description: 'Poor model design',
    scenario: 'Complex joins in BI',
    impact: 'Slow performance',
    rootCause: 'No star schema',
    solution: 'BI-optimized model',
    tools: 'Star schema',
  },
  {
    id: 7,
    title: 'Query Optimization',
    description: 'Inefficient queries',
    scenario: 'Large scans on tables',
    impact: 'High latency',
    rootCause: 'No indexing',
    solution: 'Optimize queries',
    tools: 'Delta, Z-ORDER',
  },
  {
    id: 8,
    title: 'Data Volume',
    description: 'Large dataset in BI tool',
    scenario: 'PBIX file too large',
    impact: 'Crash/slow',
    rootCause: 'No aggregation',
    solution: 'Aggregation tables',
    tools: 'Power BI',
  },
  {
    id: 9,
    title: 'Row-Level Security',
    description: 'No user-based filtering',
    scenario: 'All users see all data',
    impact: 'Security risk',
    rootCause: 'No RLS',
    solution: 'Implement RLS',
    tools: 'Power BI, UC',
  },
  {
    id: 10,
    title: 'Column-Level Security',
    description: 'Sensitive fields exposed',
    scenario: 'Salary visible to all',
    impact: 'Compliance issue',
    rootCause: 'No CLS',
    solution: 'Masking policies',
    tools: 'Unity Catalog',
  },
  {
    id: 11,
    title: 'Data Refresh',
    description: 'Failed refresh jobs',
    scenario: 'Dashboard not updated',
    impact: 'Wrong insights',
    rootCause: 'Weak pipeline',
    solution: 'Monitor refresh jobs',
    tools: 'Power BI Gateway',
  },
  {
    id: 12,
    title: 'Data Duplication',
    description: 'Multiple datasets',
    scenario: 'Same report built differently',
    impact: 'Inconsistency',
    rootCause: 'No central dataset',
    solution: 'Single source dataset',
    tools: 'Lakehouse',
  },
  {
    id: 13,
    title: 'Visualization Design',
    description: 'Poor UI/UX',
    scenario: 'Cluttered dashboard',
    impact: 'Low adoption',
    rootCause: 'No design standard',
    solution: 'UX best practices',
    tools: 'Tableau, Power BI',
  },
  {
    id: 14,
    title: 'Overloading Dashboard',
    description: 'Too many visuals',
    scenario: '50 charts in one report',
    impact: 'Confusion',
    rootCause: 'No design discipline',
    solution: 'Minimal design',
    tools: 'BI tools',
  },
  {
    id: 15,
    title: 'Drill-down Issues',
    description: 'Cannot drill deeper',
    scenario: 'No detail view',
    impact: 'Limited analysis',
    rootCause: 'Poor data modeling',
    solution: 'Drill-through design',
    tools: 'BI tools',
  },
  {
    id: 16,
    title: 'Filtering Issues',
    description: 'Filters not working correctly',
    scenario: 'Wrong subset of data',
    impact: 'Misleading insights',
    rootCause: 'Poor filter design',
    solution: 'Standard filters',
    tools: 'BI tools',
  },
  {
    id: 17,
    title: 'Data Granularity',
    description: 'Wrong level of detail',
    scenario: 'Only aggregated data',
    impact: 'No drill-down',
    rootCause: 'No granularity design',
    solution: 'Multi-level modeling',
    tools: 'Gold layer',
  },
  {
    id: 18,
    title: 'Time Intelligence',
    description: 'Incorrect time calculations',
    scenario: 'Wrong YoY growth',
    impact: 'Misleading insights',
    rootCause: 'No time dimension',
    solution: 'Time dimension table',
    tools: 'BI tools',
  },
  {
    id: 19,
    title: 'Data Governance',
    description: 'No control over reports',
    scenario: 'Anyone creates reports',
    impact: 'Chaos',
    rootCause: 'No governance',
    solution: 'Report governance',
    tools: 'BI governance',
  },
  {
    id: 20,
    title: 'Access Control',
    description: 'Unauthorized access',
    scenario: 'Reports shared publicly',
    impact: 'Security risk',
    rootCause: 'Weak IAM',
    solution: 'Secure sharing',
    tools: 'BI tools',
  },
  {
    id: 21,
    title: 'Version Control',
    description: 'Report changes not tracked',
    scenario: 'Old version used',
    impact: 'Confusion',
    rootCause: 'No versioning',
    solution: 'Version control',
    tools: 'Git',
  },
  {
    id: 22,
    title: 'Testing',
    description: 'No dashboard testing',
    scenario: 'Errors in production',
    impact: 'Risk',
    rootCause: 'No testing',
    solution: 'Validation checks',
    tools: 'QA framework',
  },
  {
    id: 23,
    title: 'Data Lineage',
    description: 'No trace from dashboard to source',
    scenario: 'Cannot debug issue',
    impact: 'Delay',
    rootCause: 'No lineage',
    solution: 'Lineage tracking',
    tools: 'Unity Catalog',
  },
  {
    id: 24,
    title: 'User Adoption',
    description: 'Low usage of dashboards',
    scenario: 'Business ignores reports',
    impact: 'No ROI',
    rootCause: 'Poor UX/trust',
    solution: 'Training + usability',
    tools: 'BI tools',
  },
  {
    id: 25,
    title: 'Mobile Optimization',
    description: 'Not mobile-friendly',
    scenario: 'Dashboard unusable on phone',
    impact: 'Poor UX',
    rootCause: 'No mobile design',
    solution: 'Responsive design',
    tools: 'Power BI',
  },
  {
    id: 26,
    title: 'Cost',
    description: 'High BI cost',
    scenario: 'Large dataset queries expensive',
    impact: 'Budget issue',
    rootCause: 'Inefficient queries',
    solution: 'Optimize queries',
    tools: 'FinOps',
  },
  {
    id: 27,
    title: 'Export Issues',
    description: 'Data export mismatch',
    scenario: 'Excel export differs',
    impact: 'Trust issue',
    rootCause: 'Transformation mismatch',
    solution: 'Standard export logic',
    tools: 'BI tools',
  },
  {
    id: 28,
    title: 'Real-time Visualization',
    description: 'No real-time dashboard',
    scenario: 'Cannot monitor live system',
    impact: 'Delay',
    rootCause: 'No streaming',
    solution: 'Real-time dashboards',
    tools: 'Kafka + BI',
  },
  {
    id: 29,
    title: 'Multi-source Integration',
    description: 'Data from multiple sources inconsistent',
    scenario: 'CRM vs ERP mismatch',
    impact: 'Confusion',
    rootCause: 'No integration model',
    solution: 'Unified data model',
    tools: 'ETL',
  },
  {
    id: 30,
    title: 'Metadata Awareness',
    description: "Users don't understand data",
    scenario: 'Misinterpretation',
    impact: 'Wrong decisions',
    rootCause: 'No metadata visibility',
    solution: 'Metadata in reports',
    tools: 'BI tools',
  },
  {
    id: 31,
    title: 'Alerting',
    description: 'No alerts on KPI change',
    scenario: 'Issues detected late',
    impact: 'Risk',
    rootCause: 'No alert system',
    solution: 'KPI alerts',
    tools: 'Power BI',
  },
  {
    id: 32,
    title: 'Personalization',
    description: 'Same dashboard for all users',
    scenario: 'Irrelevant insights',
    impact: 'Low adoption',
    rootCause: 'No personalization',
    solution: 'Role-based dashboards',
    tools: 'BI tools',
  },
  {
    id: 33,
    title: 'Data Security',
    description: 'Sensitive insights exposed',
    scenario: 'Financial report leaked',
    impact: 'Risk',
    rootCause: 'Weak governance',
    solution: 'Secure dashboards',
    tools: 'IAM',
  },
  {
    id: 34,
    title: 'Dashboard Maintenance',
    description: 'Hard to update reports',
    scenario: 'Frequent breakage',
    impact: 'Maintenance overhead',
    rootCause: 'Poor design',
    solution: 'Modular dashboards',
    tools: 'BI tools',
  },
  {
    id: 35,
    title: 'Cross-Platform Issues',
    description: 'Tableau vs Power BI mismatch',
    scenario: 'Different numbers',
    impact: 'Confusion',
    rootCause: 'No standardization',
    solution: 'Unified logic',
    tools: 'dbt',
  },
  {
    id: 36,
    title: 'Query Concurrency',
    description: 'Multiple users slow system',
    scenario: 'Dashboard hangs',
    impact: 'Poor performance',
    rootCause: 'Resource contention',
    solution: 'Scaling + caching',
    tools: 'Databricks SQL',
  },
  {
    id: 37,
    title: 'Data Sync Issues',
    description: 'Dashboard not synced with backend',
    scenario: 'Data mismatch',
    impact: 'Trust issue',
    rootCause: 'Pipeline delay',
    solution: 'Sync monitoring',
    tools: 'Monitoring tools',
  },
  {
    id: 38,
    title: 'Visualization Standards',
    description: 'No standard templates',
    scenario: 'Different layouts everywhere',
    impact: 'Inconsistency',
    rootCause: 'No standards',
    solution: 'Design system',
    tools: 'BI tools',
  },
  {
    id: 39,
    title: 'AI Integration',
    description: 'No AI insights',
    scenario: 'Static dashboards only',
    impact: 'Missed opportunity',
    rootCause: 'No AI integration',
    solution: 'AI-powered insights',
    tools: 'ML integration',
  },
  {
    id: 40,
    title: 'Explainability',
    description: "Users don't trust data",
    scenario: '"How is this calculated?"',
    impact: 'Low trust',
    rootCause: 'No explanation layer',
    solution: 'Explainable metrics',
    tools: 'Semantic layer',
  },
];

function VisualizationChallenges() {
  return (
    <ChallengeLibrary
      pageTitle="Data Visualization — 40 Challenges"
      pageSubtitle="Enterprise visualization challenges (performance, RLS, semantic layer, adoption) with architect-level playbooks."
      statsLabel="Visualization Challenges"
      totalCount={40}
      challenges={CHALLENGES}
      domain="governance"
      csvName="visualization-challenges.csv"
    />
  );
}

export default VisualizationChallenges;
